### ISSUE TITLE
Page=NaN when building custom pagination-controls-component

### ISSUE THREAD

**Issue by rmcsharry** [michaelbromley/ngx-pagination#125]
**Angular 2 version**:
2.4
**ng2-pagination version**:
2.0.0
**Description of issue**:
Paging does not work, page numbers are NaN
**Steps to reproduce**:
Create a custom pager control by copying and pasting the example template and ts code.
**Expected result**:
Page numbers should be numbers
**Actual result**:
Page=NaN

Any relevant code:
```
import {Component, Input, Output, EventEmitter, ChangeDetectionStrategy, ViewEncapsulation} from '@angular/core';

@Component({
    selector: 'fb-pager-controls', <- my own custom name
    templateUrl: './pager-controls.html', <- identical template to the one in the readme
    changeDetection: ChangeDetectionStrategy.OnPush,
    encapsulation: ViewEncapsulation.None
})
export class PagerControlsComponent { ...same code as in examples }
```

Then I use it like this:

```
<fb-pager-controls (pageChange)="getPage($event)" id="server" previousLabel="PREV">
</fb-pager-controls>

<div class="list-group">
  <fb-customer-list-item #myList *ngFor="let customer of customers | paginate: { id: 'server', itemsPerPage: 10, currentPage: pageNumber, totalItems: records }" 
    [customer]="customer">
  </fb-customer-list-item>
</div>
```

Note that I tried this: 
```
previousLabel="TEST" 
```
and the label does NOT change. So it seems that the PaginationApi is just ignoring me?

This is the getPage code in the component I am using the pager:

```
  getPage(page: number){
    console.log("Page is " + page);
    this.pageNumber = page;
    this._customerService.getCustomersPaged(page)
      .subscribe(
        customers => this.customers = customers,
        error => this.errorMessage = <any>error
      );
  }
```

It first logs Page is 1, then immediately afterwards Page is NaN.

The Server receives /customers?page=NaN.

The template also only renders 
< >

the two arrows, no page numbers, no 'next' or 'prev' labels either.

I have a feeling there is something crucial missing from the setup guide.

The standard control works just fine:
```
<pagination-controls (pageChange)="getPage($event)" id="server" previousLabel="TEST">
</pagination-controls>
```

**Comment by rmcsharry** [comment]
I have managed to use the standard control to get the styling and functionality I needed, so taking a look at this is not urgent.

Fantastic control by the way, very easy to implement, excellent guide, thank you so much!

**Comment by michaelbromley** [comment]
Hi,

I am missing the actual code for your custom control. You say it is the same as the example, but it would help if you could explicitly include the exact code you are using.

One thing to note is that the `PaginationControlsDirective` has no implementation for labels (next, prev etc) - these need to be implemented by the user.

**Comment by rmcsharry** [comment]
_

> I am missing the actual code for your custom control.

_ 

It is **identical** to your example in the readme, as I said in the steps to reproduce this:

**Create a custom pager control by copying and pasting the example template and ts code.**

**Comment by michaelbromley** [comment]
> It is identical to your example in the readme

This is what I don't get. The code in the readme is the template HTML code only. I cannot copy and paste just the template code and have a working reproduction of the issue. To be completely unambiguous, I will copy the code which I refer to here into this thread:

```HTML
<pagination-template #p="paginationApi"
                     (pageChange)="pageChange.emit($event)">

        <div class="pagination-previous" [class.disabled]="p.isFirstPage()">
            <a *ngIf="!p.isFirstPage()" (click)="p.previous()"> < </a>
        </div>

        <div *ngFor="let page of p.pages" [class.current]="p.getCurrent() === page.value">
            <a (click)="p.setCurrent(page.value)" *ngIf="p.getCurrent() !== page.value">
                <span>{{ page.label }}</span>
            </a>
            <div *ngIf="p.getCurrent() === page.value">
                <span>{{ page.label }}</span>
            </div>
        </div>

        <div class="pagination-next" [class.disabled]="p.isLastPage()">
            <a *ngIf="!p.isLastPage()" (click)="p.next()"> > </a>
        </div>

</pagination-template>
```

So, for example, there is no implementation of a `previousLabel` binding, and of course no TS code to provide outputs for the pageChange event.

Please clarify.

**Comment by rmcsharry** [comment]
This is the TS code:

https://github.com/michaelbromley/ng2-pagination/blob/master/src/pagination-controls.component.ts

You can see line 32 declares previousLabel

**Comment by michaelbromley** [comment]
Hi,

To be honest I feel a bit confused by this issue. From what I understand so far:

* You tried to use the [PaginationControlsDirective](https://github.com/michaelbromley/ng2-pagination#paginationcontrolsdirective) to create a custom controls component.
* You used the TS code from the PaginationControlsComponent, but with your own template HTML.
* The `pageChange` event fires, but with a value of `NaN`
* Also the `previousLabel` binding does not work.

At this stage it would be really helpful if you could reproduce the issue with a  [Plunker demo](http://plnkr.co/edit/JVQMPvV8z2brCIzdG3N4?p=preview), as I cannot determine why this is happening from the information provided so far.

**Comment by rmcsharry** [comment]
Yes @michaelbromley Michael, the steps you list are exactly what I did. Its so long ago now I'm not sure I can reproduce it. Also I just upgraded to your new version of the control. Best to close this I think.

**Comment by farzaneHashemi** [comment]
despite this issue is closed but I thought maybe my solution to this issue could help someone somewhere in the world :D 

since I used to have more than one table with pagination in my html page, I had to specify my pagination tag with an `id` attribute, but I forgot to put it on my `<tr>` tag as well, and that was the problem which used to cause NaN value for my `$event` . here is my code:
```
 <table>
<tbody>
    <tr *ngFor="let request of requests | paginate: { itemsPerPage: 10, currentPage: p2, id: 'history' }; let i = index">
                                  // put your <td> tags here...
    </tr>
</tbody>
</table>
<pagination-controls previousLabel="pre" nextLabel="next" (pageChange)="p2 = $event" maxSize="9" directionLinks="true" id="history"></pagination-controls>
```
