### ISSUE TITLE
has no exported member 'Ng2PaginationModule'.

### ISSUE THREAD

**Issue by DystecMX** [michaelbromley/ngx-pagination#137]
Hi, I really like your paginator but I can't use it, I have tried many ways to make it work but always come to errors.

**Angular 2 version**:
angular-cli: 1.0.0-beta.25.5

**ng2-pagination version**:
"ng2-pagination": "^2.0.1",

I'm getting the following error when trying to use ng2-pagination:
Module '"/node_modules/ng2-pagination/index"' has no exported member 'Ng2PaginationModule'.
[default] Checking finished with 1 errors.

my app.module.ts has the following:

```TypeScript
import { Ng2PaginationModule } from 'ng2-pagination';

@NgModule({
    declarations: [
        AppComponent
    ],
    imports: [
        BrowserModule,
        Ng2PaginationModule
    ],
    providers: [
    ],
    bootstrap: [AppComponent]
})
export class AppModule { }
```

Hope you can help me with this.

Thanks!

**Comment by michaelbromley** [comment]
Closing due to lack of response. Also, try v3.0.0 (now named ngx-pagination) as I have changed the way the module is bundled, which may solve your issue.
