### ISSUE TITLE
trigger pagechange event from script

### ISSUE THREAD

**Issue by devilsuraj** [michaelbromley/ngx-pagination#140]
Hi , Thanks for providing this nice component, i am just having a problem with route parameter probably there must be a solution available , let me know if i am doing something wrong

**Angular 2 version**: 2.4.0

**ng2-pagination version**: 2.0.1

**Description of issue**: When router parameter changed getpage(page) method is called but page doesnt change.

**Steps to reproduce**: create a page with pagination , but values from server a re filtered with parameters so when that parameter changes getpage should get 1st page based on those parameters

**Expected result**: it should display first page of new data from server.

**Actual result**: nothing happens

Any relevant code:
```
    this.sub = this.route.params.subscribe(params => {
       this.id = +params['id'];
        this.p=1;
         this.getPage(this.p);
  });

 getPage(page: number) {
  console.log("fired") // it reahces here when route parameter changes
     this.loading=true;
            this.artList =  this.getserverdatafor(this.id, page)
            .do(res => {
                this.total = res.pages ;
                this.p = page;
                this.loading = false;
                 })
            .map(x => x.message);
    
 }
```

**Comment by michaelbromley** [comment]
Can you show the template code too where you use the pagination controls?

**Comment by devilsuraj** [comment]
@michaelbromley 
hi sorry for delayed reply .. its as below

**Item Template**
```
<masonry [options]="myOptions">
       <masonry-brick class="brick"  *ngFor="let item of artList | async | paginate: { id: 'server', itemsPerPage: 2, currentPage: p, totalItems:  total }">
      <a  class="left black-text"
      ....
</masonry>
</masonry>

```

**Pager**
```
<div class="has-text-centered">
    <div class="spinner" [ngClass]="{ 'hidden': !loading }"></div>
    <pagination-controls (pageChange)="getPage($event)" id="server"></pagination-controls>
</div>
```

masonry  is another component i am using but it works when i click new page on template

**Comment by michaelbromley** [comment]
Hi,

You say that
> getpage(page) method is called but page doesnt change.
 
I am wondering whether the server call gets made. Also if you set a breakpoint in the `.do()` block, does it get triggered?

I cannot see an obvious problem. If you could reproduce the issue somehow in a plunker demo, that would be really helpful.

**Comment by devilsuraj** [comment]
No server call is not made it throws error at it saying isscalar false , and idea ? Can share repo if you need !

**Comment by devilsuraj** [comment]
i dont think its related to ng2-pagination because the exception i am getting is 
Exception: TypeError: 'caller' and 'arguments' are restricted function properties and cannot be accessed in this context. at Function.remoteFunction

**Comment by devilsuraj** [comment]
well the problem is with .do only it calls do but can not call http.get method network call is never made . but if its .subscribe everything works except pagination :x , is there any way where i can use .subscribe than .do

**Comment by michaelbromley** [comment]
The `async` pipe performs the `.subscribe()` call, so you don't have to.

I'm going to close this as it is more of a support request rather than an issue with this library, as you mentioned. Good luck fixing your code.
