### ISSUE TITLE
Pagination-controls relevant with others pagination-controls inside one page

### ISSUE THREAD

**Issue by aziz1117** [michaelbromley/ngx-pagination#141]
I use pagination-controls inside card. I have more than three card on a page, when I click on one pagination-controls it will change the others inside this page.
How I can use pagination-controls separately from other pagination-controls.
Thank you.

**Comment by michaelbromley** [comment]
Give each pagination pipe/controls pair a unique id, and this will allow them to operate independently. Read over [this part of the docs again](https://github.com/michaelbromley/ng2-pagination#api) for more detail.

**Comment by yinonov** [comment]
using a uniqe id helps when using the 'pagination-controls' component but when using a custom control with the [original code](https://github.com/michaelbromley/ng2-pagination/blob/master/src/pagination-controls.component.ts) it fails.

any idea why?

**Comment by yinonov** [comment]
An issue I encountered on using custom component and such unique id approach -
the example on the [documentation](https://github.com/michaelbromley/ng2-pagination) is missing the 'id' and 'maxSize' attribute:
`<pagination-template #p="paginationApi"
                     (pageChange)="pageChange.emit($event)">`

fixed by editing to actual existing template:
`<pagination-template class="controls" #p="paginationApi"
                     [id]="id" 
                     [maxSize]="maxSize" 
                     (pageChange)="pageChange.emit($event)">`

**Comment by michaelbromley** [comment]
@yinonov The readme does include the following:

---
It has the following inputs and outputs:
```
@Input() id: string;
@Input() maxSize: number;
@Output() pageChange: EventEmitter<number>;
```
---

I'm not sure whether including them in the example would be more or less clear. I can imagine people opening issues saying "Where does the "id" in `[id]="id"` come from?"

I think I will add a section to the docs about how to do multiple instances, which should cover all use cases.

**Comment by michaelbromley** [comment]
Readme updated with section on multiple instances.
