### ISSUE TITLE
Having "Previous" and "Next" Buttons Grey-out Along with Arrows

### ISSUE THREAD

**Issue by darrenbrett** [michaelbromley/ngx-pagination#145]
Hi and thanks for the great out-of-the-box functionality offered with ng2-pagination. I've got it working like a charm now in my Angular 2 app.

My one styling/functionality issue is that right now only the arrows are greying-out when disabled (i.e. when the user has reached either the first or last page of results). Currently on my app the "Previous" and "Next" buttons are not greying out like the arrows are. On your examples I see that they should be greying out. Any idea what's causing this and how I can address it?

This is what I currently have in my view code:

`<tr *ngFor="let record of records.data | paginate: { id: 'clients', itemsPerPage: 12, currentPage: page, totalItems: records.count }">`

And ...

```
<pagination-controls class="paginator" (pageChange)="pageChange($event)" id="clients"
          maxSize="15"
          directionLinks="true"
          autoHide="true">
</pagination-controls>
```

Thanks again for a great module!

**Comment by michaelbromley** [comment]
Hi, glad you got things working!

I am not totally sure what "arrows" you mean. In the default template, the "previous" and "next" text is part of the same button as the arrows. They should all grey out together, [see the basic demo](http://michaelbromley.github.io/ng2-pagination/#/basic). Do you maybe have some custom styling which may be preventing this?

**Comment by michaelbromley** [comment]
I'm closing this issue because further data was needed but was not provided. If you want to continue the thread, let me know and I'll re-open it.
