### ISSUE TITLE
Unexpected padding and custom template doesn't work

### ISSUE THREAD

**Issue by mohitook** [michaelbromley/ngx-pagination#146]
=======
Hello!

**Angular version**:

**ngx-pagination version**: latest

**Description of issue**: custom template doesn't look like on the demo page

**Steps to reproduce**: use the template in a bootstrap panel footer

**Expected result**: looks great

**Actual result**:
![image](https://cloud.githubusercontent.com/assets/15103326/25070841/222c4fa8-22a9-11e7-990d-7d6537f52190.png)

**Demo**: 
http://plnkr.co/edit/ofLDnQI9PTUDpfvOJHod?p=preview

Any relevant code:
you can see in the plnkr

Additional question:
I could use the default, but there is a 40px padding which shifts the whole thing right and I can't get rid of it.. as I've found it out from chrome debug tools the css is here: pagination-controls > pagination-template > ul... but I can't redefine the padding...

Thanks!

**Comment by thaihacong** [comment]
Confirmed. I also have exactly this problem on v3.0.0.

**Comment by mohitook** [comment]
@thaihacong Thanks for the workaround, now it is in one line but still doesn't really looks like it should.. :(

**Comment by michaelbromley** [comment]
Hi,

If you create your own paging controls based on the `PaginationControlsDirective`, you must style it yourself with your own css. Defining css is not a "work around" - it is the intended procedure.

Regarding the default controls (`PaginationControlsComponent`), I am not sure where this "40px padding" comes from - there is no such padding defined [in the default styles](https://github.com/michaelbromley/ngx-pagination/blob/9b456cf1a21bce6a33569c7cbf1c68befa28a422/src/template.ts#L49). Perhaps it is coming from some of your existing css? If you are using Bootstrap, it is very possible that the Bootstrap css for pagination may be interfering with things.

Hope that helps.

**Comment by mohitook** [comment]
@michaelbromley Thanks, in this case could you share the css you use in the example? It looks really good and many of us is not a css master :( . It may provide a good basic of how can we create our own style.

**Comment by michaelbromley** [comment]
Sure, here is the css used in the custom example ([source](https://github.com/michaelbromley/ngx-pagination/blob/9b456cf1a21bce6a33569c7cbf1c68befa28a422/docs/src/style.scss#L89-L107)):

```Sass
.custom-pagination {
    display: flex;
    max-width: 300px;
    margin: auto;

    > div {
        flex: 1;
        font-size: 18px;
        text-align: center;
        border-bottom: 3px solid transparent;
        -moz-user-select: none;
        -webkit-user-select: none;
        -ms-user-select: none;
    }

    > div.current {
        border-color: #3dffaf;
    }
}
```

That's very basic, but you can use it as a basis for your own styles. Good luck!
