### ISSUE TITLE
Facing problem in property of paginate 

### ISSUE THREAD

**Issue by abinavaraamK** [michaelbromley/ngx-pagination#148]
======
angular-cli": "1.0.0-beta.28.3",
**Angular version**:^2

**ngx-pagination version**:3.0.0

**Description of issue**:  i have included the ngx-pagination in my app module and in import ,but while trying to build i am facing issue for a property inside the paginate pipe  

**Steps to reproduce**:

**Expected result**:pagination should work 

**Actual result**:while building i am getting Property 'p' does not exist on type 'ClassName'

**Demo**: (if possible, edit [this Plunker demo](http://plnkr.co/edit/JVQMPvV8z2brCIzdG3N4?p=preview) and paste the link to your fork)

Any relevant code:
```
app.module.ts

import { Ng2PaginationModule } from 'ng2-pagination';

...

@NgModule({
  imports: [
    BrowserModule,
    Ng2PaginationModule,
    FormsModule,
    HttpModule
  ],
...

.ts file 
        public currentPage:number;
	public totalItems:number ;
  	public itemsPerPage:number;

.html file 
	<tr *ngFor="let customer of filteredCustomers | paginate :{itemsPerPage: itemsPerPage, currentPage: p }">

<pagination-controls (pageChange)="p = $event"
                      directionLinks="true"
                      autoHide="false"
                      previousLabel="Previous"
                      nextLabel="Next">
	</pagination-controls>
```
This Issue is happening with --aot not with JIT

**Comment by michaelbromley** [comment]
Hi,

The error message pretty much tells you what's wrong. In your template you are binding the current page to a property named "p", but in your TS code you have named it "currentPage".

**Comment by abinavaraamK** [comment]
Yup Thanks
