### ISSUE TITLE
CSS style for pagination-controls not working

### ISSUE THREAD

**Issue by codecypher** [michaelbromley/ngx-pagination#149]
Hi, thanks for contributing!

This project is maintained in my spare time, so in order to help me address your issue as quickly as 
possible, please provide as much of the following information as you can.

-- Michael 

[^ delete this message]

=======

**Angular version**: 2.4.5

**ngx-pagination version**: 3.0.0

**Description of issue**: Trying to apply custom CSS to pagination-controls not being applied.

**Steps to reproduce**: Just try applying some style to the pagination-controls. Nothing seems to take effect.

**Expected result**: Would like to be able to change font-size and use glyph-icons for Next, Previous, First, and Last like the [CSS First Last, Next Prev Sample](http://brantwills.github.io/Angular-Paging/) . I am unable to get the angular-paging library working with Visual Studio so I would like to use your library if I can style it properly.

**Actual result**: Nothing happens when I try to apply CSS styles.

**Demo**: (if possible, edit [this Plunker demo](http://plnkr.co/edit/JVQMPvV8z2brCIzdG3N4?p=preview) and paste the link to your fork)

http://plnkr.co/edit/yu2tnDevHidsW5VB6pIQ?p=preview

Any relevant code:
```

```

**Comment by michaelbromley** [comment]
Hi there,

You are right, the advice given in the readme was incorrect. If your component uses emulated or shadow DOM view encapsulation (and emulated is the default if not specified), then you'll need to use the `/deep/` operator to target the styles. I've [updated the readme](https://github.com/michaelbromley/ngx-pagination/blob/cc12fb0497d0b5dde68f7fb5543da23b1df55126/README.md#styling) now to reflect this.

**Comment by twarchal** [comment]
Hi there,

How then change color of pagination control text . I've tried this but not working :

.my-pagination /deep/ .ngx-pagination  {
    color:red;
}

Thanks in advance
