### ISSUE TITLE
stringFilter Pipe not found

### ISSUE THREAD

**Issue by daemswibowo** [michaelbromley/ngx-pagination#152]
I followed step from this http://michaelbromley.github.io/ngx-pagination/#/advanced
i got this error :

```
ERROR Error: Uncaught (in promise): Error: Template parse errors:
The pipe 'stringFilter' could not be found ("
                		</thead>
                		<tbody>
                			<tr *ngFor="let [ERROR ->]item of items | async | paginate: config | stringFilter: filter">
                				<td>{{ item.nam"): ng:///UserModule/UserComponent.html@29:35
Error: Template parse errors:
The pipe 'stringFilter' could not be found ("
                		</thead>
                		<tbody>
                			<tr *ngFor="let [ERROR ->]item of items | async | paginate: config | stringFilter: filter">
                				<td>{{ item.nam"): ng:///UserModule/UserComponent.html@29:35
```
Any other  suggestions to create the filter? Thanks

**Comment by michaelbromley** [comment]
Hi,

You need to define the pipe yourself - it is not built-in to Angular. You can use the [implementation which I use in the demo](https://github.com/michaelbromley/ngx-pagination/blob/53873521a37b2eb82e851da28c7828532da70004/docs/src/string-filter.pipe.ts).

**Comment by eurolife** [comment]
Can you better explain this? how to define the pipe? I also followed the steps in your demo/example and got the same error. I tried creating a pipe named 'paginate' using the code here https://github.com/michaelbromley/ngx-pagination/blob/53873521a37b2eb82e851da28c7828532da70004/docs/src/string-filter.pipe.ts but it still can't find 'paginate'. I clearly missed something, what step have I missed?

**Comment by daemswibowo** [comment]
thanks @michaelbromley for the answer.

hi @eurolife, you dont need to create  a new paginate pipes.
This is my search filter pipes, this nicely work with firebase list too :
```
@Pipe({
  name: 'searchPipe'
})
export class searchPipe implements PipeTransform {
  transform(items:any[], args:any):any[] {
    var isSearch = (data:any): boolean => {
      var isAll = false;
      if(typeof data === 'object' ){
        for (var z in data) {
          if(isAll = isSearch(data[z]) ){
            break;
          }
        }
      } else {
        if(typeof args === 'number'){
          isAll = data === args;
        } else {
          isAll = data.toString().match( new RegExp(args, 'i') );
        }
      } 

      return isAll;
    };

    return items.filter(isSearch);
  }
}
```
Don't forget to add your pipes to your module. I hope this helps you :)

**Comment by michaelbromley** [comment]
@eurolife it sounds like you might be missing out on some general Angular understanding. I'm afraid I've not got time to go into depth on this, since it is not directly related to this library. I suggest you go through the [official docs on pipes](https://angular.io/docs/ts/latest/guide/pipes.html) and see if that helps.
