### ISSUE TITLE
How can to change text 'Next', 'Previous'?

### ISSUE THREAD

**Issue by thanhngvpt** [michaelbromley/ngx-pagination#154]
Hi All.
I want to translate (or simply replace text to display) text 'Next', 'Previous' in pagination control.
Many thanks.

=======

**Angular version**: 4.0.3

**ngx-pagination version**:3.0.0

**Comment by michaelbromley** [comment]
Hi. See [the docs](https://github.com/michaelbromley/ngx-pagination/tree/4cf8e63a4c4c8dbb7018c5075af81518529c7faf#paginationcontrolscomponent) - you just need to set the `nextLabel` and `previousLabel` attributes.

**Comment by thanhngvpt** [comment]
Thanks @michaelbromley
