### ISSUE TITLE
server side pagination not firing http once we get 0 list

### ISSUE THREAD

**Issue by skumarcdac** [michaelbromley/ngx-pagination#156]
=======

**Angular version**:4

**ngx-pagination version**:3

**Description of issue**:Once we get the 0 list from server after that it don't fire http service

**Steps to reproduce**: let's say this service method return an 0 items based on search. After that we are searching on new filter and making a call to this method again but it doesn't fire the http method
```TypeScript
pagedItems: Observable<string[]>;
 getPage(page: number) {
       let request: Pagination = new Pagination();
        request.page = page;
        request.resultsPerPage = 10;
        request.search = vm.searchModel;
 this.pagedItems = service.getPage(JSON.stringify(request), page)
            .do(res => {
                    vm.total = res.json().count;
                    vm.p = page;
                    vm.count = vm.total;
            })
            .map(res => res.json().data);
}
 getPage(request: string, page: number): Observable<Response> {
    let endpoint = 'http://localhost:8080/job/listAll/pagination/'+page;
        return this.http.post(endpoint, request)
            .map((response: Response) => {
                return response;
            });
    }
```
so once I get the 0 count from service({"data":[],"count":0}) after that it stopped firing http call.. however when i debug it  go to getPage() method but doesn't fire http. 
```HTML
<tr *ngFor="let item of pagedItems  | async | paginate: { id: 'server', itemsPerPage: 10, currentPage: p, totalItems: total }" >
 <td>{{item}}</td>
</tr>
<pagination-controls (pageChange)="getPage($event)" id="server"></pagination-controls>
```
**Expected result**:it suppose to fire http request based on new search value

**Actual result**:

**Demo**: (if possible, edit [this Plunker demo](http://plnkr.co/edit/JVQMPvV8z2brCIzdG3N4?p=preview) and paste the link to your fork)

Any relevant code:
```

```

**Comment by michaelbromley** [comment]
Hi,

This looks like a general support request rather than an issue specifically related to this project. Unfortunately I don't have time to field such requests, and a better source of assistance would be [StackOverflow](http://stackoverflow.com/).

If you think I've made a mistake and this is indeed an issue specific to this project, let me know and I will re-open and look at this again.
