### ISSUE TITLE
Route Property

### ISSUE THREAD

**Issue by ozknozsrt** [michaelbromley/ngx-pagination#160]
**Angular version**:
4.1.3

**ngx-pagination version**:
3.0.0

**Steps to reproduce**: 
Hi, First of all thank you very much! Is it possible to add a router as a property?

**Comment by michaelbromley** [comment]
Hi,

I am not sure what you mean. Can you elaborate? Maybe with an example of how you would like it to work?

**Comment by ozknozsrt** [comment]
I mean a suggestion. So like location path routing 👍

**Comment by michaelbromley** [comment]
Sorry for the delay. This is something you could do by means of a custom template. It will not be supported by the default template since it is too implementation-specific.

**Comment by ozknozsrt** [comment]
Okay, thanks for feedback 👍
