### ISSUE TITLE
How can I get the total items or last page ? 

### ISSUE THREAD

**Issue by armandoaepp** [michaelbromley/ngx-pagination#166]
I need to get the last page from the component if it were not possible, the total items.
I'm working on data memory

```
 class="body" *ngFor="let row of rows | searchPipe: filter | paginate: configPagination "

 <pagination-controls [id]="configPagination.id"
                             [maxSize]="paramsPagination.maxSize"
                             [directionLinks]="paramsPagination.directionLinks"
                             [autoHide]="paramsPagination.autoHide"
                             [previousLabel]="labels.previousLabel"
                             [nextLabel]="labels.nextLabel"
                             [screenReaderPaginationLabel]="labels.screenReaderPaginationLabel"
                             [screenReaderPageLabel]="labels.screenReaderPageLabel"
                             [screenReaderCurrentLabel]="labels.screenReaderCurrentLabel"
                             (pageChange)="onPageChange($event)"></pagination-controls>
```
necesito optener la utlima pagina desde el componente si no fuera posible, el total de items. 
Estoy trabajando en memoria los datos.

**Comment by michaelbromley** [comment]
Hola,

I just had a look into this, and I found this StackOverflow thread: https://stackoverflow.com/questions/35127257/how-to-get-the-size-of-a-filtered-piped-set-in-angular2 - basically there seems to be no simple way to get a count of a collection which is filtered by a pipe, but there are some work-arounds given there that you may be able to use.
