### ISSUE TITLE
Control of how many values are shown

### ISSUE THREAD

**Issue by ialex90** [michaelbromley/ngx-pagination#167]
Hi, thanks for this library, it's great to use.

Is there a way to know (by the lib) how many elements are shown on the pagination? Let's say I paginate by 10 but only 5 elements are shown because there is not more data, that's ok, do I have control of that number of registers rendered?

More than an issue just a question, I didn't see this info on the documentation, please feel free to close it once you replied to it as it's not a real bug but something that might interest someone else.

Cheers,

**Comment by michaelbromley** [comment]
Hi,

No, there is no way currently built-in to the lib that would allow this, but there is a kinda work-around which you could use. Something like this (code not tested, but just for the concept):

```HTML
<li *ngFor="let item of items | paginate: config" #row>...</li>
```

```TypeScript
@ViewChildren('row') rows: QueryList<ElementRef>;

// ...
get rowCount(): number {
  return this.rows.length;
}
```
