### ISSUE TITLE
Update totalItems does not update pageNumber (server-side)

### ISSUE THREAD

**Issue by emreavsar** [michaelbromley/ngx-pagination#169]
**Angular version**:
4.2.x

**ngx-pagination version**:
v3.0.0

**Description of issue**:
I'm using the server side pagination example and it works fine. When I'm updating the totalItems (after adding an item for example) the number of pages does not get updated when totalItems is exceeding the currentpages.

**Example:**
```
  paginationConfig: PaginationInstance = {
    currentPage: 1,
    itemsPerPage: 5,
  };
```

Total Items initial call returns for example: 50. => 10 pages à 5 items => OK

Backend call returns now +1 => should result in 11 pages, it does not.

**Steps to reproduce**:
- Implement server side pagination as it is in example
- add a function which simulates a backend call which returns totalItems += 1
- set totalItems of config to the returned response from simulated backend call
- no change on page 

**Expected result**:
updated pages.

**Actual result**:
no update in pages

**Comment by michaelbromley** [comment]
Hi,

I cannot reproduce the behaviour you report. See [this demo](http://plnkr.co/edit/SXfQx4AFYComCv40USju?p=preview) - increasing the value of `totalItems` does indeed alter the number of page links, as expected.

Maybe take a look at what your code does differently. Perhaps it could just be a change detection issue?

**Comment by emreavsar** [comment]
This is not server side, i already checked it non-server side and this worked for me as well.

I tried to update your plunkr a bit, now you have some strange behaviour: http://plnkr.co/edit/9Aod7CYbyop6ZemuC44k?p=preview

- Go to last page
- add some items
-> page numbers do not update
- go 1 page back
-> page numbers somehow update
- go to next page -> something not ok

of course the example is a bit limited, but i think you get the point?

**Comment by michaelbromley** [comment]
Hi,

There were a few errors in that example. I fixed them up and now I hope you'll find that it works as expected: http://plnkr.co/edit/5RZChpU7C48ZKd7u4bNx?p=preview

Let me know if you need any more help.

**Comment by emreavsar** [comment]
Oh yeah, you're right. That's quite interesting. I have to compare this with my solution to figure out what I'm doing wrong then.

I'll update this issue then.

**Comment by emreavsar** [comment]
And thanks.
