### ISSUE TITLE
Auto-hide custom pagination-template

### ISSUE THREAD

**Issue by rob-weiss** [michaelbromley/ngx-pagination#171]
While it is well explained how to auto-hide the pagination using the `pagination-controls` component, I can't figure out how to do it using the custom `pagination-template`.

I basically copied the [example](http://michaelbromley.github.io/ngx-pagination/#/custom-template) and changed some inner HTML [like so](https://github.com/rob-weiss/Data-Visualisation/blob/master/Implementation/App/Client/app/components/list/stack-list/stack-list.component.html). It's working fine but how can I auto-hide the custom pagination component?

**Comment by michaelbromley** [comment]
Hi,

The "auto hide" feature is just something implemented in the default controls component. If you want similar functionality in your own custom template, you need to implement it yourself. Luckily it is quite simple - see [here how I do it](https://github.com/michaelbromley/ngx-pagination/blob/5d86183fd178915cac9a88c2900177709eae39b9/src/template.ts#L14).

So in your case you could modify your current template code like this:

```HTML
 <div class="d-flex justify-content-center"  *ngIf="p.pages.length > 1">
```

**Comment by rob-weiss** [comment]
Awesome! Thanks a lot Michael! I appreciate your work and quick response!
