### ISSUE TITLE
error running ng build --prod

### ISSUE THREAD

**Issue by JesseSoldat** [michaelbromley/ngx-pagination#172]
Hi Micheal,
Thanks for making this cool product.  Anyway it works as expected when I run ng build using the cli.  However when I run ng build --prod I get an error listed below.

**ngx-pagination version**:     "ngx-pagination": "^3.0.1",

**Description of issue**: angular cli build for production ng build --prod
when I run ng build (not production) there is no problem

Any relevant code:
----------------------------------------------------------------
ERROR in ng:/ campaigns.component.html (63,7): Property 'p' does not exist on type 'CampaignsComponent'.

ERROR in ng:/7 campaigns.component.html (37,15): Property 'p' does not exist on type 'CampaignsComponent'.
----------------------------------------------------------------
html 
line 37
 <tr *ngFor="let col of rows | orderBy: order | paginate: { itemsPerPage: 5, currentPage: p }">

line 63
<pagination-controls class="pull-right"
      (pageChange)="p = $event">
      </pagination-controls> 
 
Package JSON
"@angular/common": "^4.0.0",
    "@angular/compiler": "^4.0.0",
    "@angular/core": "^4.0.0",
    "@angular/forms": "^4.0.0",
    "@angular/http": "^4.0.0",
    "@angular/platform-browser": "^4.0.0",
    "@angular/platform-browser-dynamic": "^4.0.0",
    "@angular/router": "^4.0.0",
    "bootstrap": "^3.3.7",
    "core-js": "^2.4.1",
    "font-awesome": "^4.7.0",
    "jquery": "^3.2.1",
    "ngx-order-pipe": "^1.0.1",
    "ngx-pagination": "^3.0.1",
    "rxjs": "^5.1.0",
    "zone.js": "^0.8.4"

  "devDependencies": {
    "@angular/cli": "1.0.4",
    "@angular/compiler-cli": "^4.0.0",
    "@types/jasmine": "2.5.38",
    "@types/node": "~6.0.60",
    "codelyzer": "~2.0.0",
    "jasmine-core": "~2.5.2",
    "jasmine-spec-reporter": "~3.2.0",
    "karma": "~1.4.1",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^0.2.0",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.0",
    "ts-node": "~2.0.0",
    "tslint": "~4.5.0",
    "typescript": "~2.2.0"
  }

Thanks for your time
Jesse Soldat

**Comment by michaelbromley** [comment]
Hi,

The error message is quite helpful here: check whether there is a property `p` defined on the `CampaignsComponent`. 

In JIT mode (the regular `ng build`), the compiler does not care when you declare variables in the template which do not exist on the class. In prod mode however, it is more strict and you are not allowed to use variables in the template unless they are also declared on the class. This is because in prod mode, the templates themselves get compiled into TypeScript classes.

Let me know if that helps.

**Comment by pageii** [comment]
@michaelbromley That helped.
