### ISSUE TITLE
Angular 4.2.4 Error : The pipe 'paginate' could not be found

### ISSUE THREAD

**Issue by hsbalar** [michaelbromley/ngx-pagination#173]
```
>  <ul>
>       <li *ngFor="let item of collection | paginate: { itemsPerPage: 10, currentPage: p }"> 
>       </li>
>  </ul>
```

**Comment by michaelbromley** [comment]
Hi,

Are you including the `NgxPaginationModule` in your app module?

**Comment by hsbalar** [comment]
Yes I'm including it

**Comment by michaelbromley** [comment]
Ok. You'll need to provide some more context for me, then. Show me your module definition, and the component which the above template comes from. If those files are very large, please include only the relevant parts.

**Comment by hsbalar** [comment]
I have included `NgxPaginationModule` in my app module, and I have one lazy load module where I'm using pagination, does it make any problem ?

**Comment by michaelbromley** [comment]
Okay. Perhaps the lazy loading is causing an issue. In this case, it should be safe to directly import the `NgxPaginationModule` into the lazy-loaded module, either directly or via a shared module if you use that pattern.

**Comment by hsbalar** [comment]
Yes I have shared module.
Thanks @michaelbromley

**Comment by hsbalar** [comment]
I have to use it in lazy-loaded module, It not working if I defined it to Shared module or Root level module.
Thanks @michaelbromley

**Comment by michaelbromley** [comment]
You're welcome. Is this resolved now? If so, you can close the issue.

**Comment by hsbalar** [comment]
Yes it is resolved.

**Comment by midhun-george** [comment]
Is it possible to remove that pagination pipe conditionally?
for example: In mobile view, I don't want any pagination

**Comment by michaelbromley** [comment]
@midhun-george this question is out of the scope of this library - it is a general Angular question "is it possible to apply a pipe conditionally?" I suggest you ask on StackOverflow.

**Comment by midhun-george** [comment]
thanks

**Comment by aaju** [comment]
Hi,
I had same issue.
I have resolved it through adding NgxPaginationModule in lazyloading module.
But when i run ng build --prod.
I get " ERROR in : The pipe 'paginate' could not be found (" 
Can you please help.
Thanks
