### ISSUE TITLE
Pagination not working in some instances

### ISSUE THREAD

**Issue by kennethmitchelljr** [michaelbromley/ngx-pagination#176]
Hi Michael,

In my current application I have used multiple instances of ngx-pagination. It works perfectly fine on the main pages of the application, but then when I go deeper into the application with a couple of clicks and try to use pagination, it doesn't go past page 1. I am currently trying to paginate a table and have made use of the 'id' attribute also, but still have no luck. Any suggestions on how to resolve this current issue I am having. Let me know if you need any more details on the current issue.

**Comment by michaelbromley** [comment]
Hi,

Yes, I would need a bit more info in order to help, such as: 

* any error messages in the console
* relevant bits of template / component code

Ideally a reproduction of the issue, but I understand that sometimes the complexity of the setup makes this difficult.

**Comment by kennethmitchelljr** [comment]
Sounds good,
I am not getting an error in the console. But an example of the code I have is below. What is happening is when I have for example 15 contacts. It does show the first 5, but when I click to see the next set of 5 it flickers to the 2nd page for a millisecond and just goes back to page 1. 

![image](https://user-images.githubusercontent.com/17212996/28580156-b35d33d0-712c-11e7-8c8b-5b047717e37f.png)

And I have 3 other instances of pagination in that same file that looks similar. In my typescript file I just have `p: number = 1;` Let me know if you need anything else.

**Comment by kennethmitchelljr** [comment]
Hey Michael,
I was able to figure out my issue. The problem was that in all my instances for `<pagination-controls>` were referencing the same p variable for the `currentPage` and the `(pageChange)` event which is what gave me the bug I was having. Simply changing the name of it solved the issue!

**Comment by michaelbromley** [comment]
Okay, glad you got it fixed!
