### ISSUE TITLE
Edit DEFAULT_STYLES and DEFAULT_TEMPLATE

### ISSUE THREAD

**Issue by parloti** [michaelbromley/ngx-pagination#177]
Are there any easy ways to edit DEFAULT_STYLES and DEFAULT_TEMPLATE?

Simply add pagination-template inside pagination-controls, break the APP.

> Unhandled Promise rejection: Can not assign a reference or variable! ; Zone: <root>; Task: Promise.then; Value:

=======

**Angular version**: 2.4

**ngx-pagination version**: 3.0.1

**Description of issue**:

**Steps to reproduce**:

**Expected result**:

**Actual result**:

**Demo**: (if possible, edit [this Plunker demo](http://plnkr.co/edit/JVQMPvV8z2brCIzdG3N4?p=preview) and paste the link to your fork)

Any relevant code:
```

```

**Comment by michaelbromley** [comment]
Hi,

They are not designed to be edited. If you want something other than the defaults, create a custom control as [covered in the docs](https://github.com/michaelbromley/ngx-pagination/tree/5d86183fd178915cac9a88c2900177709eae39b9#paginationcontrolsdirective).

For simple CSS changes, you can always just override the default styles. This is also [covered in the docs](https://github.com/michaelbromley/ngx-pagination/tree/5d86183fd178915cac9a88c2900177709eae39b9#styling).

> Simply add pagination-template inside pagination-controls, break the APP.

Sounds like you might be doing something wrong here. If you show me the code you are trying, I'll be able to advise further.

**Comment by parloti** [comment]
Okay, I got the error.
