### ISSUE TITLE
error running ng  build --prod

### ISSUE THREAD

**Issue by trung674** [michaelbromley/ngx-pagination#179]
Hi Micheal, 

I got this strange error after executing `ng build --prod --sm`. Do you, by any chance, have any idea what happened here ? 

```
ERROR in vendor.278d412fd1e057aaa26f.bundle.js from UglifyJs
Unexpected token: operator (>) [/mnt/d/Coding/class-management-angular/src/$$_gendir/~/ngx-pagination/dist/ngx-pagination.ngfactory.ts:13,25][vendor.278d412fd1e057aaa26f.bundle.js:30758,184]
```

=======

**Angular version**:  4.3.3

**ngx-pagination version**: 3.0.1

**Comment by michaelbromley** [comment]
Hi,

Sorry, I don't know what the problem is just from the information provided. Have you tried looking in `ngx-pagination.ngfactory.ts:13,25` to see what is there which is being complained about?

**Comment by trung674** [comment]
Hi,

I guess the error is pointed to this file `node_modules/ngx-pagination/dist/ngx-pagination.d.ts` 

```
/**
 * Generated bundle index. Do not edit.
 */
export * from './ngx-pagination.module';
export { DEFAULT_STYLES as ɵb, DEFAULT_TEMPLATE as ɵa } from './template';
```

and here is the content of `ngx-pagination.module.d.ts`
```
export { PaginationInstance } from './pagination-instance';
export { PaginationService } from './pagination.service';
export { PaginationControlsComponent } from './pagination-controls.component';
export { PaginationControlsDirective } from './pagination-controls.directive';
export { PaginatePipe } from './paginate.pipe';
export declare class NgxPaginationModule {
}
```

Nothing seems strange though. :(

**Comment by trung674** [comment]
I found the reason. I accidentally set the build stage to `es2015` instead of `es5`. I changed back and everything run perfectly now. Please close this.

**Comment by Fabiyo-90** [comment]
Please May ou show me how did you do ?

**Comment by Fabiyo-90** [comment]
Please may you show us how did you do ?

**Comment by trung674** [comment]
@Fabiyo-90 When you create an angular app with Angular CLI, there is a file called `tsconfig.json` in the root folder. What I did wrong was to set the `target` value in `compilerOptions` to `es2015` instead of the default `es5`. I later changed back and everything worked normally.
