### ISSUE TITLE
ERROR RangeError: Maximum call stack size exceeded - Custom Pagination Template

### ISSUE THREAD

**Issue by justinedehonor** [michaelbromley/ngx-pagination#180]
**Angular version**: 4.0.0

**ngx-pagination version**: 3.0.1

**Description of issue**: _ERROR RangeError: Maximum call stack size exceeded_ is encountered using custom pagination template. _NOTE: Using the default pagination-controls works fine._

**Steps to reproduce**: Copy and paste the example on how to build a custom template

**Expected result**: Next and Previous are working together with the collection data

**Actual result**: Error encountered: ERROR RangeError: Maximum call stack size exceeded

**Demo**: (if possible, edit [this Plunker demo](http://plnkr.co/edit/JVQMPvV8z2brCIzdG3N4?p=preview) and paste the link to your fork)

Any relevant code:

**car.component.html**
```
<ul>
    <li *ngFor="let car of cars | paginate: { itemsPerPage: 10, currentPage: p }">{{ car.name }}</li>
</ul>

<pagination-template #p="paginationApi"
(pageChange)="pageChange.emit($event)">

<div class="pagination-previous" [class.disabled]="p.isFirstPage()">
    <a *ngIf="!p.isFirstPage()" (click)="p.previous()"> &lt; Previous Page </a>
</div>

<div *ngFor="let page of p.pages" [class.current]="p.getCurrent() === page.value">
    <a (click)="p.setCurrent(page.value)" *ngIf="p.getCurrent() !== page.value">
        <span>{{ page.label }}</span>
    </a>
    <div *ngIf="p.getCurrent() === page.value">
        <span>{{ page.label }}</span>
    </div>
</div>

<div class="pagination-next" [class.disabled]="p.isLastPage()">
    <a *ngIf="!p.isLastPage()" (click)="p.next()"> Next Page &gt; </a>
</div>

</pagination-template> `
```

**car.component.ts**
```
import { Component, OnInit } from '@angular/core';
import { Car } from '../../interfaces/car';
import { Router } from '@angular/router';

@Component({
  selector: 'app-car',
  templateUrl: './car.component.html',
  styleUrls: ['./car.component.css']
})
export class CarComponent implements OnInit {
  
  private cars: Car[];
  private p: Number = 1;
  
  constructor(private carService: CarService, private router: Router) { }
  
  ngOnInit() {
    this.carService.getAllCars().subscribe((cars: Car[]) => this.cars = cars);
  }
  
  onClick(car: Car) : void {
    this.router.navigate(['/cars', car.id]);
  }
  
}
```

**Comment by michaelbromley** [comment]
Hi,

You have assigned the variable `p` to both the page number and the local template variable for thw pagination API. Try using unique variable names.

**Comment by justinedehonor** [comment]
Hi,

Thank you for your response.

After changing the variable, the collection data was displayed correctly. However, **ERROR TypeError: Cannot read property 'emit' of undefined** is encountered when navigating to other pages.

I created a variable in the component but still no luck
`private pageChange: EventEmitter<number>;`

**Comment by michaelbromley** [comment]
Hi,

If you do:

```TypeScript
private pageChange: EventEmitter<number>;
```

You are declaring a class field and declaring its type, but you are not assigning it a value. Therefore it is always undefined, which explains the error you see.

It should read:
```TypeScript
private pageChange = new EventEmitter<number>();
```
However, in your case I don't think you want to re-emit the pageChange event, rather you want to actually update the value of `p`, which can be done like so:

```
(pageChange)="p = $event"
```
and then you don't even need the EventEmitter at all.

**Comment by justinedehonor** [comment]
Hi,

It is now working perfectly! Thank you!
