### ISSUE TITLE
Reset pagination to first page

### ISSUE THREAD

**Issue by anshulkayastha** [michaelbromley/ngx-pagination#182]
I am using ngx-pagination with server side paging. So, user enters some search criteria and hits the search button. This results in a call to the server for the first page of the results. On the client side, I have this code to show the pagination controls

```
 <div class="col-sm-4">
        <pagination-controls (pageChange)="getPage($event)" id="serverPaging" ></pagination-controls>
      </div>

 <div *ngFor="let result of results | paginate: { id:'serverPaging', itemsPerPage: 10, currentPage: p, totalItems: totalResultCount }"
              >...</div>
```
This works as expected. The first page is shown and '1' in the pagination bar is highlighted.

Lets say, user now clicks on last page. This would highlight the last page in the pagination bar. Everything works as expected so far.

Now user re-executes the search by clicking on the 'Search' button again. This re-renders the search results. Since it's a fresh search, server returns the first page. However, pagination bar still has the last page highlighted.

How can I reset the pagination bar to the first page on some action, like re-execution of search. 

Angular version: 4.2.4
ngx-pagination version: 3.0.0

**Comment by michaelbromley** [comment]
Hi,

In the method which performs the search, can you not just set `this.p = 1;`?

**Comment by skottawar** [comment]
@michaelbromley  thank dude!
