### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by sergey-morenets** [michaelbromley/ngx-pagination#186]
Hi 

I tried to install the latest version of ngx-pagination and observed different warnings in the console during process. It didn't stop the installation but could you please explain why it happened and how to remove them?

**Angular version**:

4.3.4

**ngx-pagination version**:

3.0.1

**Log warnings**:

WARN registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning EINTEGRITY: sha512-+vD6E8ixntRzzZukoF3uP1iV+ZjVN3koTcaeK+BEoc/kSfGbLDIGC7RmCaUgVpUfN6cWvfczFRERCyKM9mkvXg== integrity checksum failed when using sha512: wanted sha512-+vD6E8ixntRzzZukoF3uP1iV+ZjVN3koTcaeK+BEoc/kSfGbLDIGC7RmCaUgVpUfN6cWvfczFRERCyKM9mkvXg== but got sha1-XUo/V5wVJOAe4hv0dOb7oJGY9HA=. (29797 bytes)

**Comment by michaelbromley** [comment]
Hi,

This looks like an npm issue. See https://github.com/npm/npm/issues/17146 on the npm repo for more info and possible fixes.

**Comment by sergey-morenets** [comment]
Hi @michaelbromley 

Thank you, it helped.
