### ISSUE TITLE
Drop down pagination

### ISSUE THREAD

**Issue by vishalkumars** [michaelbromley/ngx-pagination#187]
Hi,
I am trying to display pagination based on user select dropdown.
Lets say if there are 100 records, if i select 15 from select dropdown list, it should display in 7 pages,if i select 50 then it should display in 2 pages and if i select 100 it should display only one 1 page.

This is what i did,
<tr *ngFor="let x of mf.data|paginate: {itemsPerPage: row, currentPage:page}; let i = index;">

<pagination-controls (pageChange)="page = $event"  maxSize="7" class="pagination_footer"
                       directionLinks="true"
                       autoHide="true"></pagination-controls>

My html

  <label class="label-control" style="margin-top:3px;">Results per page</label>
        <select class="form-control input-sm results-page" [(ngModel)]="rowsOnPage">
          <option *ngFor="let row of rowsOnPageSet"  [value]="row" >{{ row }}</option>
      </select>

In the component.ts i am defining   public rowsOnPageSet = [15,30,50,100,500];

When i start the app and select 30 from dropdown , i can see 30 records on 1st pagebut the other pages are returing null and in the pagination tab it is showing infinty.

Can you help me with this ?

=======

**Angular version**:

**ngx-pagination version**:

**Description of issue**:

**Steps to reproduce**:

**Expected result**:

**Actual result**:

**Demo**: (if possible, edit [this Plunker demo](http://plnkr.co/edit/JVQMPvV8z2brCIzdG3N4?p=preview) and paste the link to your fork)

Any relevant code:
```

```

**Comment by michaelbromley** [comment]
Hi,

I could help you if you provide a [plunker demo](http://plnkr.co/edit/JVQMPvV8z2brCIzdG3N4?p=preview) reproducing the issue.

**Comment by vishalkumars** [comment]
Hi Michael,
Updated plunkr http://plnkr.co/edit/b7CZHaYKpP7B92J04ITV?p=preview

**Comment by michaelbromley** [comment]
Thanks. See this updated plunker which now works: http://plnkr.co/edit/N3qd0LY05r7N5iBFqgbz?p=preview

The problem was this bit:
```HTML
<li *ngFor="let item of collection | paginate: { itemsPerPage: rowsOnPageSet, currentPage: p }">{{ item }}</li>
```

You were binding `itemsPerPage` (which expects an integer) to the array `rowsOnPageSet`.

**Comment by vishalkumars** [comment]
Thanks alot Micheal,it worked.
