### ISSUE TITLE
Pagination is not working as expected

### ISSUE THREAD

**Issue by shaaafi** [michaelbromley/ngx-pagination#191]
=======

**Angular version**: 4.0.0

**ngx-pagination version**:3.0.1

**Description of issue**:  I take data from server  and save data into a blog variable . When my page initializes  , only the 'Next' directionLink is showed rather than my data with the pagination panel . After I click on 'Next' directionLink , then my data and pagination panel appear and work properly

**Steps to reproduce**:

**Expected result**:
![b1](https://user-images.githubusercontent.com/20613730/30006330-f9585878-9117-11e7-9175-8021a3e604e5.PNG)

Please click on mage of expected result

**Actual result**:

![b2](https://user-images.githubusercontent.com/20613730/30006333-0592837a-9118-11e7-8fd7-01b3df128896.PNG)

Please click on  the image of expected result

Any relevant code:
```
/////////////////////////my home.component.ts

import {ChangeDetectionStrategy, Component, Input, OnInit } from '@angular/core';
import { ProductService } from '../../services/product.service';
import { Router } from '@angular/router';
import { DatePipe } from '@angular/common'

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.css'],
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class HomeComponent implements OnInit {
  page: number = 1;
  blogs: any;

  constructor(public blogService:ProductService) { 
   
  }

  ngOnInit() {
   
    this.blogService.getAllBlog().subscribe((res)=>{
      this.blogs=res.data;
        console.log(res);
    });
  }


}

/////////////////////////////////////my home.component.html

<div class="text-center jumbotron">
    <div class="page-header">
        <h1>Your Favourite Blog</h1>
        <h2>Authentic Substantial Doubtless</h2>
    </div>
    <h3>Please Login in order to Post blog</h3>
    <a  class="btn btn-primary btn-lg" style="margin-right: 20px"><span class="glyphicon glyphicon-log-in"></span> LogIn</a>
    <a  class="btn btn-primary btn-lg"><span class="glyphicon glyphicon-user"></span>  Register</a>
</div>

<div class="container" id="my-padding">
    <div *ngIf="blogs">
        <div class="row">
            <div class="col-md-4" *ngFor="let blog of blogs | paginate: { itemsPerPage: 9, currentPage: page, id:'foo' }">
                <div>
                    <a [routerLink]="['/detailBlog',blog._id]">
                        <div class="thumbnail">
                            <img src="{{blog.avatarPath}}" alt="avatar">
                            <div class="caption">
                                <h4 id="title">Title : {{blog.title}}</h4>
                                <h5>Author: {{blog.auther.name}}</h5>
                                <p>Created At: {{blog.createdAt | date:'medium'}}</p>
                            </div>
                        </div>
                    </a>
                </div>
            </div>

        </div>
    </div>
</div>
<div style="text-align: center">
    <pagination-controls id="foo" (pageChange)="page = $event" directionLinks="true"></pagination-controls>
</div>


```

**Comment by michaelbromley** [comment]
Hi,

This looks like it could be related to change detection. I notice you are using "OnPush", so the component will not be updated unless one of its inputs change or an event is fired from within it - and there are no inputs, so only the click event is triggering the change detection.

So I would recommend either:
1. Use the default changeDetectionStrategy or
2. Inject the changeDetectorRef and in the subscribe function, call `this.changeDetectorRef.markForCheck()`.

**Comment by abhijithrkrishnan** [comment]
Hi,
@michaelbromley 
I am also having the same issue.  I tried with your suggestions, but the resulted same.

I have another issue too.
Numbers are not updating in the pagination panel with the selected page number.
Eg:  When I limit maxSize to 5 (or any number), and we have 27 pages (any higher number) than the maxSize.  
Initially the panel is:
                               << Previous 1 2 3 ... 27 Next >> with 1 as selected.
Its fine with this.

When I select page 3,

Expected Panel:
                              << Previous  2 3 4 ... 27 Next >>with 3 as selected.

But I am getting
                             << Previous 1 2 3 ... 27 Next >> with 3 as selected.

Firstly, sorry for not attaching any photos.  Do I need to write a custom component to get rid of this. Am new to the domain and I am stuck with this issues. Thanks for the help in advance.
Abhijith.
