### ISSUE TITLE
How to load a page number from a saved url param

### ISSUE THREAD

**Issue by darrenbrett** [michaelbromley/ngx-pagination#193]
Hi Michael,

I've been using your ng2-pagination for quite a while now, and so far it's been working like a charm. However, I'm running into an issue now while adding some additional functionality that I'd like to get your feedback on. 

In the app I am saving various params in the URL, so that a user can re-load a page of data - with their last selected filters already applied. I've got that working for the filters. However, I also want to pass in the page number as well. Right now, while I can retrieve the page number from the url, I am having difficulty figuring out how to pass that back into your pagination tool so that the right page of data will load. 

My template code where I'm using the pagination tool looks like this:

`<tr *ngFor="let record of records.data | paginate: { id: 'stream', itemsPerPage: 12, currentPage: this.page, totalItems: records.count }">`

Along with this...

```
    <div *ngIf="records?.data" class="pagination">
        <pagination-controls class="paginator" (pageChange)="pageChange($event)" 
            id="stream"
            maxSize="12"
            directionLinks="true"
            autoHide="true">
        </pagination-controls>
    </div>
```

My pageChange() function, where I handle emitting between components, looks like this:

```
    pageChange(page)
    {
        this.sendChange.emit(page);
        console.log(this.page);
    }
```

So, right now, I am able to scroll through the pages produced by the paginate tool, and those are successfully passed on to the URL. In other words, if I start on page 1, and then use the paginate tool pages to go to page, 2, 3, 4, etc, all that is passed into the url successfully, and the correct data loads - whether I go forward or backward, or whether I click on the generated page numbers, or the "Previous" or "Next" buttons. So all that's good to go.

However, where I run into an issue is if I refresh the page. In that case I want the page number reflected in the url params  to pass back into the paginate tool, so it'll load the appropriate data. In other words, if the url looks like this: 

> http://localhost:4200/clients;page=4

... I want to pass that page number back into the params for the pagination, so that the data appropriate for page 4 loads.

 Any idea how I should go about doing this?

I've tried first retrieving the page # from the url params, like so:

```
    getPageByParams()
    {
        this.route.params.subscribe(
            (params: any) => {
                this.page = params['page'] || 0;
            });
            console.log(this.page);
            return this.page;
    }
```

And then assigning "currentPage" in the pagination to that, like this:

`<tr *ngFor="let record of records.data | paginate: { id: 'stream', itemsPerPage: 12, currentPage: getPageByParams(), totalItems: records.count }">`

But this didn't work. In this case, this approach results in no page number highlighted, and without the correct data loading.

I did some additional testing, and even if I hardcode in the page number in the component, by making it something like:

page = 17;

And then use this code in the view:

`<tr *ngFor="let record of records.data | paginate: { id: 'stream', itemsPerPage: 12, currentPage: this.page, totalItems: records.count }">`

... while "17" is correctly highlighted upon refresh of the page in the page numbers of the view, the actual data is unchanged. In other words, it looks like it's still loading the initial data, regardless of what page number is highlighted with the hardcoding of the page number in the component for "this.page".

So perhaps I'm misunderstanding how your pagination tools handles the logic?

Any idea how I can handle this situation where I want to pass in a page number from a url param?

Thanks again for the great extension!

**Comment by michaelbromley** [comment]
Hi Darren,

Okay, so first of all, what you want to achieve is totally doable. I do it in several of my own applications.

> So perhaps I'm misunderstanding how your pagination tools handles the logic?

There is really nothing special going on. It takes the `currentPage` value and the `itemsPerPage` value and uses it to calculate how to slice up your source array (for in-memory paging) and otherwise how to render the page links.

To me it sounds like there is a problem with keeping the `currentPage` value in sync with the rest of the app state. I'll outline how I arrange things to give you an idea:

```TypeScript
@Component({
    selector: 'my-component',
    template: `
        <ul>
            <li *ngFor="let item of items$ | async | paginate: { itemsPerPage: 12, currentPage: currentPage, totalItems: totalItems }">...</li>
        </ul>
        <pagination-controls (pageChange)="pageChanged($event)"></pagination-controls>
    `
})
class MyComponent {
    currentPage: number;
    totalItems: number;
    items$: Observable<any[]>;

    constructor(private route: ActivatedRoute,
                private router: Router,
                private apiService: ApiService) {
        
        this.items$ = this.route.params
            .map(params => params['page'])
            .do(page => this.currentPage = page)
            .switchMap(page => this.apiService.getPage(page))
            .do(response => this.totalItems = response.totalItems)
            .map(response => reponse.items);
    }

    pageChanged(newPage: number) {
        this.router.navigate(['./currentPath', newPage]);
    }
}

```

So the idea here is that the only thing that can trigger a change to the `currentPage` value is actually updating the URL. When this happens, you can follow the stream of effects given by this block:

```TypeScript
   this.items$ = this.route.params
            .map(params => params['page'])
            .do(page => this.currentPage = page)
            .switchMap(page => this.apiService.getPage(page))
            .do(response => this.totalItems = response.totalItems)
            .map(response => reponse.items);
```

The above will:
1. Get the current page from the URL params
2. Assign that to the `currentPage` variable
3. Use that value to make a server call and wait for the response (assuming some service which makes a HTTP call and returns an Observable or a Promise)
4. Assigns the `totalItems` variable based on the server response.
5. Maps that stream into a stream of items which can then be plugged into the template with the async pipe.

I've not tested that code but in my mental compiler it seems like it should work.

I hope that helps and is not too confusing!

**Comment by andrei-sadagurschi** [comment]
Hello,

@michaelbromley 
I am trying to do the same exact thing. I've tried the example you suggested. The data is loading correctly for a specific page, but the correct page is not highlighted. Please see the attached screenshot (page 10 was loaded in this case).

Thank you!
![screen shot 2017-09-28 at 2 04 44 pm](https://user-images.githubusercontent.com/2855014/30963470-2c22a6a4-a456-11e7-83d3-dd991b738308.png)

**Comment by andrei-sadagurschi** [comment]
One more thing... The pagination control in this case let's me click on the page 10. The event that I receive in this case is a change from page 10 to page 10 and the correct page item is highlighted.
![screen shot 2017-09-28 at 2 08 55 pm](https://user-images.githubusercontent.com/2855014/30963568-98e4498c-a456-11e7-8581-e7c2e639d31e.png)

**Comment by andrei-sadagurschi** [comment]
Just discovered that if I try to load a page greater than the max page, let's say 20 in my case where the max is 18, I receive to page change events from 20 to 18 then another one from 18 to 18 and the correct page item is highlighted.

**Comment by michaelbromley** [comment]
@andrei-sadagurschi Sounds like some kind of change detection issue. Is your component using the OnPush strategy?

Regarding your last comment, I think this is related to https://github.com/michaelbromley/ngx-pagination/issues/155#issuecomment-301873473 - the two page change events are not ideal.

**Comment by andrei-sadagurschi** [comment]
@michaelbromley No, I am not using OnPush strategy, but I was looking into other related problems.
#190 fixes my problem. The current page was initially passed as a string and not as a number after getting it from the query params. Converting it to a number fixed the highlight issue.

**Comment by andrei-sadagurschi** [comment]
Thank you for the quick response 👍 I don't mind the two page change events when the tried page is out of bounds.

**Comment by michaelbromley** [comment]
@andrei-sadagurschi okay, since this has come up a couple of times I think I'd better fix this by checking the input type and parsing as a number if a string is passed. I'll do this in the next update, whenever that is.

**Comment by andrei-sadagurschi** [comment]
Yes, I think that would be useful. Thank you!

**Comment by darrenbrett** [comment]
Yes, I ran into the same thing -- eventually realized the issue was that I needed to convert the string into a number -- then my paging worked in terms of passing back in the correct page number.

**Comment by bawse** [comment]
I also ran into this problem and fixed it by explicitly converting the string to a number, which worked and highlighted the correct page number.

**Comment by michaelbromley** [comment]
This is now fixed in master and in the next release you won't need to worry about converting strings to numbers. Unfortunately I ran into some issues last time I wanted to do a release, but I hope to get the release out soon.
