### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by djjaysmith** [michaelbromley/ngx-pagination#195]
Unable to install ngx-pagination
[2017-09-13T10_46_56_734Z-debug.zip](https://github.com/michaelbromley/ngx-pagination/files/1299159/2017-09-13T10_46_56_734Z-debug.zip)

Hi,

I tried to install this for a project I am working on and I get a series of errors;

verbose stack Error: EPERM: operation not permitted, lstat
verbose Windows_NT 6.1.7601
verbose argv "F:\\Program Files\\nodejs\\node.exe" "C:\\Users\\jason\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "ngx-pagination" "--save"
verbose node v6.11.3
verbose npm  v5.3.0
error path F:\Users\jason\Documents\Development\Angular2\wishindex\node_modules\fsevents\node_modules
1087 error code EPERM
error errno -4048
 error syscall lstat
error Error: EPERM: operation not permitted, lstat 'F:\Users\jason\Documents\Development\Angular2\wishindex\node_modules\fsevents\node_modules'
error     at Error (native)
error  { Error: EPERM: operation not permitted, lstat 'F:\Users\jason\Documents\Development\Angular2\wishindex\node_modules\fsevents\node_modules'
error     at Error (native)
error   stack: 'Error: EPERM: operation not permitted, lstat \'F:\\Users\\jason\\Documents\\Development\\Angular2\\wishindex\\node_modules\\fsevents\\node_modules\'\n    at Error (native)',
error   errno: -4048,
error   code: 'EPERM',
error   syscall: 'lstat',
error   path: 'F:\\Users\\jason\\Documents\\Development\\Angular2\\wishindex\\node_modules\\fsevents\\node_modules' }
error Please try running this command again as root/Administrator.
verbose exit [ -4048, true ]

Attached is the log file;

**Comment by michaelbromley** [comment]
I sometimes get EPERM errors on Windows if I have e.g. Webpack watch mode running. It basically means something is doing something with the node_modules dir and when npm tries to modify it to do an install, it is not allowed.

**Comment by djjaysmith** [comment]
Based on this I closed down my editor (Visual Studio Code) and stopped ng serve and then tried to reinstall.  

This seems to have then worked OK.

Thanks
