### ISSUE TITLE
Pagination Controls multiply on each click

### ISSUE THREAD

**Issue by matiaskm** [michaelbromley/ngx-pagination#196]
**Angular version**: 4.3.6

**ngx-pagination version**: 3.0.1

**Description of issue**: I'm using the ngx-pagination in a table, but each time I click on the "next" button it adds the pagination component again, and so on. I'm just using the code as specified on the documentation. Thanks!

**Steps to reproduce**: Just click on "next"

**Expected result**: Change page

**Actual result**: It adds another pagination component and also, doesn't actually change the page, it just adds the elements to the actual page.

Any relevant code:
```
<tr *ngFor="let item of rows | paginate: {id: 'foo', itemsPerPage: 1, currentPage: currentPage}">
          <td *ngFor="let header of headers">{{ item[header['field']] || "- - -"}}</td>
        </tr>
      </tbody>
    </table>
    <pagination-controls id="foo" (pageChange)="currentPage = $event"></pagination-controls>

```
![screen shot 2017-09-14 at 17 41 41](https://user-images.githubusercontent.com/18614906/30455142-161f030c-9975-11e7-9b50-01e91f81cf09.png)
![screen shot 2017-09-14 at 17 42 25](https://user-images.githubusercontent.com/18614906/30455146-19de48fe-9975-11e7-98b3-715bcec0d015.png)

**Comment by michaelbromley** [comment]
Hi,

Looks weird! Could it be that the `<pagination-controls>` are inside of an ngFor loop? I'm pretty certain that this is not an issue specific to this library, rather it seems like an error in your template. I can't tell exactly what's wrong from the snippet you provided though.

**Comment by matiaskm** [comment]
Hi, yes, that's what I thought. Thank you for the library!
