### ISSUE TITLE
Question for pagination template

### ISSUE THREAD

**Issue by Meistercoach83** [michaelbromley/ngx-pagination#198]
Hello! I have a question for my pagination: I´d like to build a naviagation with the following formats:

> << | < | 1 | **2** | 3 | .... | > | >>

and

> << | < | ... | 7 | **8** | 9 | > | >>

I got evertyhing to work except the "..."-links. I want to jump to the next not displayed page (in example 1 to page four and display the navigation from that point, in example to I´d like to jump to page 6 and get the navigation for that view). Is that possible?

**Comment by michaelbromley** [comment]
Hi!

I think currently the solution for this would have to be a little bit hacky. The logic for generating the ellipses (...) is hard-coded here:

https://github.com/michaelbromley/ngx-pagination/blob/20a2db2501b842826e28031f5d0e2c894401a2b9/src/pagination-controls.directive.ts#L170-L185

so you'd have to have some do some logic in your template which (in your first example) omits the last link and (in your second example) omits the first page link.

**Comment by Belouccio** [comment]
maybe it will be heplphul

```
<li [class.current]="p.getCurrent() === page.value"
            [class.ellipsis]="page.label === '...'"
            *ngFor="let page of p.pages; trackBy: trackByIndex; let index = index; let last = last; let first === first">
            <a tabindex="0" (keyup.enter)="p.setCurrent(page.value)" (click)="p.setCurrent(page.value)" *ngIf="p.getCurrent() !== page.value && !(last && p.pages[index - 1].label === '...') && !(first && p.pages[index + 1].label === '...')">
                <span class="show-for-sr">{{ screenReaderPageLabel }} </span>
                <span>{{ (page.label === '...') ? page.label : (page.label | number:'') }}</span>
            </a>
            <ng-container *ngIf="p.getCurrent() === page.value">
                <span class="show-for-sr">{{ screenReaderCurrentLabel }} </span>
                <span>{{ (page.label === '...') ? page.label : (page.label | number:'') }}</span>
            </ng-container>
        </li>
```
