### ISSUE TITLE
Page number links not working except previous and next for 25 items per page

### ISSUE THREAD

**Issue by yogesh-aloha** [michaelbromley/ngx-pagination#201]
**Angular version**:
4.0.0
**ngx-pagination version**:
3.1.0
**Description of issue**:
Not able to click on number link in pagination  control but next and previous buttons works perfectly
**Steps to reproduce**:
when I use itemsPerPage="10" it is working but not working for itemsPerPage="25" so I debug in code and found that 
```TypeScript
this.changeSub = this.service.change
            .subscribe(function (id) {
            if (_this.id === id) {
                _this.updatePageLinks();
                _this.changeDetectorRef.markForCheck(); 
                _this.changeDetectorRef.detectChanges();
            }
        });
```

This code is contentiously calling itself which results in updating page links and I am not able to click on any page number in pagination control. again I found changeSub is uundefined here

 
**Expected result**:
This should work on all pagination links
**Actual result**:
Not working for few page link 

Any relevant code:
```HTML
  <div class="row "
                     *ngFor="let patient of patients | patientFilter: patientName | paginate: { itemsPerPage: 25, currentPage: pageNo } | orderby: {property: property, direction: sortDirection, type: type}"
                     (click)="selectPatient($event, patient)">
<div *ngIf="(patients | patientFilter: patientName).length > 0">
  /* Some code to print data*/
                <pagination-controls 
                    (pageChange)="pageNo = $event"  maxSize="9"  autoHide="true" ></pagination-controls>
                
```

**Comment by michaelbromley** [comment]
Hi,

I don't fully understand the issue. What do you mean by "I am not able to click on any page number in pagination control"? Do you mean no event is emitted when you click?

If you are able to reproduce this issue in a plunker demo, it would help me to debug.

**Comment by yogesh-aloha** [comment]
Hi 

I have created video of issue please check

http://www.screencast.com/t/GzdhEDpshAK

**Comment by michaelbromley** [comment]
Apologies for the slow response. Is this still an issue? Also I don't have flash player installed so I didn't see your video.
