### ISSUE TITLE
Warning: The specified id does not match any registered PaginationInstance

### ISSUE THREAD

**Issue by ospaarmann** [michaelbromley/ngx-pagination#203]
**Angular version**: 2.4.10

**ngx-pagination version**: 3.0.1

**Description of issue**: When following the docs precisely and using a custom id I always get the error `The specified id 'member-comments-show' does not match any registered PaginationInstance`. 

The component code: 

```
import { Component, OnInit } from '@angular/core';

import { PaginationInstance } from 'ngx-pagination';

@Component({
  moduleId: module.id,
  selector: 'member-show',
  templateUrl: 'member-show.component.html',
  styleUrls: ['member-show.component.scss']
})
export class MemberShowComponent implements OnInit {

  public config: PaginationInstance = {
    id: 'member-comments-show',
    itemsPerPage: 10,
    currentPage: 1
  };

  constructor() {}

}
```

The template part:

```
        <pagination-template #p="paginationApi" [id]="config.id" (pageChange)="getCommentsPage($event)">

          <nav>
            <ul class="pagination custom-pagination">
              <li [class.disabled]="p.isFirstPage()">
                <a *ngIf="!p.isFirstPage()" (click)="p.previous()" >
                  <span>&laquo;</span>
                </a>
                <a *ngIf="p.isFirstPage()">
                  <span>&laquo;</span>
                </a>
              <li>
              <li *ngFor="let page of p.pages" [class.active]="p.getCurrent() === page.value">
                <a (click)="p.setCurrent(page.value)" *ngIf="p.getCurrent() !== page.value">
                  <span>{{ page.label }}</span>
                </a>
                <a *ngIf="p.getCurrent() === page.value">
                  <span>{{ page.label }}</span>
                </a>
              </li>
              <li [class.disabled]="p.isLastPage()">
                <a *ngIf="!p.isLastPage()" (click)="p.next()">
                  <span aria-hidden="true">&raquo;</span>
                </a>
                <a *ngIf="p.isLastPage()">
                  <span>&raquo;</span>
                </a>
              </li>
            </ul>
          </nav>

        </pagination-template>
```
I left out some functions for brevity. 

Strangely enough I don't have this problem on other components of the same app.

**Steps to reproduce**: Just follow the exact steps in the docs.

**Expected result**: 

**Actual result**:

**Demo**: http://plnkr.co/edit/3qWursMeWTl7GPds8lxz?p=preview

**Comment by ospaarmann** [comment]
Well, stupid me. I started with the pagination without including the content to be paginated. When I did that, the issue disappeared...

**Comment by Meistercoach83** [comment]
Hi! I have the same error with the following template:

`<div class="m-datatable__pager m-datatable--paging-loaded clearfix"
                   pagination-template #p="paginationApi" [id]="config.id" (pageChange)="setPage($event)">

                <ul class="m-datatable__pager-nav">

                  <li>
                    <a [class.disabled]="p.isFirstPage()" (click)="p.setCurrent(1)"
                       class="m-datatable__pager-link m-datatable__pager-link--first m-datatable__pager-link--disabled">
                      <i class="la la-angle-double-left"></i>
                    </a>
                  </li>

                  <li>
                    <a [class.disabled]="p.isFirstPage()" (click)="p.previous()"
                       class="m-datatable__pager-link m-datatable__pager-link--prev m-datatable__pager-link--disabled">
                      <i class="la la-angle-left"></i>
                    </a>
                  </li>

                  <li style="" *ngFor="let page of p.pages">
                    <a (click)="p.setCurrent(page.value)"
                       [ngClass]="p.getCurrent() === page.value ? ' m-datatable__pager-link--active' : ''"
                       class="m-datatable__pager-link m-datatable__pager-link-number">
                      {{page.value}}
                    </a>
                  </li>
                  <li>
                    <a class="m-datatable__pager-link m-datatable__pager-link--next" [class.disabled]="p.isLastPage()"
                       (click)="p.next()">
                      <i class="la la-angle-right"></i>
                    </a>
                  </li>

                  <li>
                    <a class="m-datatable__pager-link m-datatable__pager-link--last" [class.current]="p.isLastPage()"
                       (click)="p.getLastPage()">
                      <i class="la la-angle-double-right"></i>
                    </a>
                  </li>
                </ul>
</div>`

and my component:

`public config: IPagination = {
    id: 'main',
    itemsPerPage: 10,
    currentPage: 1
  };

  setPage(pageNumber: number) {
    this.config.currentPage = pageNumber;
  }
`

I don´t have these problems in other parts, too...

**Comment by ospaarmann** [comment]
Can you post the complete template code of your component? Or just make sure that you not only added the pagination but also the actual collection to paginate (including the correct pipe). In your case that would be something like:

```

<div *ngFor="let item of items | paginate: config">
  <div>
    {{item.content}}
  </div>
</div>
```
