### ISSUE TITLE
Paginate data from parent component (logic) to child (UI)

### ISSUE THREAD

**Issue by ChaudhryAtif** [michaelbromley/ngx-pagination#204]
Hi Michael,

Thank you for all the work you have done towards this project!

I have a situation in which all of my API calls are done in parent component, and I pass the resulting data to child component to loop and display. The hurdle I'm facing is that my pagination logic for prev/next page would reside in parent, but the ngFor is being done in child component, so I'm not sure how to paginate it from parent.

**Demo**: http://plnkr.co/edit/D9A3xEZZL5fOKKlAHHmn?p=preview
Demo shows pagination works fine if logic and ngFor is in parent. I want to paginate while logic is in parent, and ngFor is in child.

I hope there is a way to accomplish this with the setup  currently have.

Overview:
```
-- parent.component.ts
collection = [];

// Make API call and store result in collection
constructor(){
  for (let i = 1; i <= 100; i++) {
    this.collection.push(`item ${i}`);
  }
}
-- parent.component.html
// Pass result from api (collection) to child
<child-component [collection]="collection"></child-component>

-- child.component.ts
@Input() collection: [];

-- child.component.html
// Paginate this
<ul>
  <li *ngFor="let item of collection">{{item}}</li>
</ul>
```

**Comment by michaelbromley** [comment]
Hi,

Sure, what you want to do can be done - you can just also pass the currentPage value down to the child component along with the collection and then use the paginate pipe in the child:

```HTML
<!-- parent.component.html -->
<pagination-controls (pageChange)="p = $event"></pagination-controls>
<child-component [collection]="collection" [currentPage]="p"></child-component>
```

```TypeScript
// child.component.ts
@Input() collection: any[] = [];
@Input() currentPage: number = 1;
```

```HTML
<!-- child.component.html -->
<ul>
  <li *ngFor="let item of collection | paginate: { currentPage: currentPage, itemsPerPage: 10 }">{{item}}</li>
</ul>
```

Working demo: http://plnkr.co/edit/xdWKa6HHqQEkWQu8oTWS?p=preview
