### ISSUE TITLE
Back to first page

### ISSUE THREAD

**Issue by bawse** [michaelbromley/ngx-pagination#208]
I am trying to build a custom pagination template using the PaginationControlsDirective, however I'm having trouble getting my head around it all.

The following is the type of pagination that I am looking for:

<<   < 1 2 3 4 5 .. >

In particular "<<" is used to skip to the first page. Is there any way to add another "button" in the pagination component which allows for this functionality?

Thank you for contributing this project!

**Comment by bawse** [comment]
Since posting the above issue, I have added the following code to the custom pagination template code which seems to give me the functionality I need in terms of skipping to first page:

`    <div class="pagination-first" [class.disabled]="p.isFirstPage()">
      <a *ngIf="!p.isFirstPage()" (click)="p.setCurrent(1)"> << </a>
    </div>`

However, the styling is no longer applied. Is there any way I can get the default template styling to work on my custom template?

**Comment by michaelbromley** [comment]
Hi,

There is no simple way to get the styling to work in your custom template, other than copy-pasting the [default styles](https://github.com/michaelbromley/ngx-pagination/blob/30a8103c2fd2baf0d7b17aaeeffaaab30f3511b3/src/template.ts#L49-L110) into your custom component's CSS and modifying as needed.

**Comment by bawse** [comment]
Hi, is there any way of showing the disabled "Prev" button in a custom template?

**Comment by michaelbromley** [comment]
Sure. What have you tried so far?
