### ISSUE TITLE
Feature request : localization (i18n)

### ISSUE THREAD

**Issue by JerryBels** [michaelbromley/ngx-pagination#209]
**Angular version**: 2+

**ngx-pagination version**: v3.0.2

**Description of the requested feature**: It would be great to be able to serve different data coming from our lang files to replace the default labels ("previous", "next", etc...). They would be passed as attributes of the `pagination-controls` directive and if present, be used in place of default values.

**Comment by michaelbromley** [comment]
Hi,

There [already is an API](https://github.com/michaelbromley/ngx-pagination/tree/d8d105a98ca1ef641c310e1e1190c853c4d2cfd6#paginationcontrolscomponent) for setting the labels. Does this not cover your use case?

**Comment by JerryBels** [comment]
Actually I completely missed this in the doc - and I don't get how, it's pretty obvious. Thanks a lot, that's awesome !
