### ISSUE TITLE
Latest release is broken?

### ISSUE THREAD

**Issue by HarelM** [michaelbromley/ngx-pagination#210]
I'm getting the following error on my build machine (I think it is new to version 3.0.2):
```
ERROR in error : Metadata version mismatch for module C:/projects/site/IsraelHiking.Web/node_modules/ngx-pagination/dist/ngx-pagination.d.ts, found version 4, expected 3
```
angular-cli 1.4.4.

More info can be seen in the build log - scroll down:
https://ci.appveyor.com/project/IsraelHikingHost/site/build/5.1.31

**Comment by shusson** [comment]
staying on version `3.0.1` avoids the issue for me

**Comment by HarelM** [comment]
I did that too, just wanted to notify the owner...

**Comment by michaelbromley** [comment]
Yes, you are right. Sorry!

I upgraded the Angular version I use to build the lib, without realizing that they switched to a new format for the metadata. I'll release a new patch version asap with compatible metadata and wait until the next major release to upgrade the Angular version.

**Comment by skorunka** [comment]
Same problem, solved by downgrade to `3.0.1`.

**Comment by michaelbromley** [comment]
Okay people, please try version 3.0.3, which has just been published to npm. Let me know if that resolves the issues for you.

**Comment by chpoit** [comment]
Seems to be fixed on my end. Thanks.

**Comment by BTAVE01** [comment]
I'm using angular 5 and the version 3.1.0 but I see the same ERROR in Metadata version mismatch for .../node_modules/@angular/core/core.d.ts, found version 4, expected 3

ERROR in ./src/main.ts
Module not found: Error: Can't resolve './$$_gendir/app.module.ngfactory' in ..../angular_components/src'
 @ ./src/main.ts 3:0-70
 @ multi ./src/main.ts

**Comment by HarelM** [comment]
I'm using version 3.1.0 now and have not issues with cli compilation.
