### ISSUE TITLE
The pipe 'paginate' could not be found || Ionic project

### ISSUE THREAD

**Issue by Rickem** [michaelbromley/ngx-pagination#212]
Hi, I'm trying to implement pagination in my ionic app, but I run into issues when I tried to use your module.

=======

**Angular version**:
**ionic-angular**: "3.7.1"
**ngx-pagination version**: "^3.0.3"

**Description of issue**: 
Error: Template parse errors:
The pipe 'paginate' could not be found ("
      <ion-row>
        <ion-col col-6 class="space" 
          *ngFor="let [ERROR ->]word of listOfSeniorWords | paginate: { itemsPerPage: 10, currentPage: p }">

Any relevant code:
```
-----> app.module.ts
import { NgxPaginationModule } from 'ngx-pagination';

@NgModule({
  declarations: [
    MyApp
  ],
  imports: [
    BrowserModule,
    HttpModule,
    NgxPaginationModule,
    IonicModule.forRoot(MyApp)
  ],

-----> words-list.ts
import { Component, ChangeDetectionStrategy, Input } from '@angular/core';
import { IonicPage, NavController} from 'ionic-angular';
import { DataProvider } from './../../providers/data/data';

@IonicPage()
@Component({
  selector: 'page-words-list',
  templateUrl: 'words-list.html',
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class WordsListPage {
  @Input('data') listOfSeniorWords: string[] = [];
  page: number = 1;

-----> words-list.html
<ion-grid>
      <ion-row>
        <ion-col col-6 class="space" 
          *ngFor="let word of listOfSeniorWords | paginate: { itemsPerPage: 10, currentPage: p }">

          <a class="word" (click)="readWord(word)">
            <p class="word-container">{{ word.mot }}</p>
          </a>
        </ion-col>
      </ion-row>
      <ion-row>
        <pagination-controls (pageChange)="p = $event"></pagination-controls>
      </ion-row>
    </ion-grid>
```
Any help would be highly appreciated. Thanks

**Comment by michaelbromley** [comment]
Hi,

The error means that the paginate pipe is not being declared in the module containing the component in which it is used (WordsListPage in this case). You are importing the `NgxPaginationModule` into your root module, but if the WordsListPage component is part of some child module, the you should really be importing the `NgxPaginationModule` into that child module, else the declarations will not be available to use there.

**Comment by Rickem** [comment]
I've tried that, but I still get the same error message.

**Comment by michaelbromley** [comment]
Hmm okay. In that case I'm not sure what else it would be. Perhaps it is something to do with Ionic, but I have literally zero experience with Ionic so that's just a guess.

Can you show me the code of the module file in which WordsListPage is declared?

**Comment by Rickem** [comment]
Here's the code:
`import { Component, ChangeDetectionStrategy, Input } from '@angular/core';
import { IonicPage, NavController} from 'ionic-angular';
import { DataProvider } from './../../providers/data/data';
import { NgxPaginationModule } from 'ngx-pagination';

@IonicPage()
@Component({
  selector: 'page-words-list',
  templateUrl: 'words-list.html',
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class WordsListPage {
  @Input('data') listOfSeniorWords: string[] = [];
  page: number = 1;
  
  constructor(
    public navCtrl: NavController,
    public data: DataProvider) {
      this.getSeniorWords();
  }

  getSeniorWords() {
    this.data.getSeniorWords().subscribe(data => this.listOfSeniorWords = data);
  }

  readWord(word) {
    this.navCtrl.push('WordsPage', word);
  }

  navigateToCategory() {
    this.navCtrl.setRoot('UserCategoryPage');
  }

}
`

**Comment by michaelbromley** [comment]
Sorry, I wasn't clear. I meant the code for the NgModule which has the WordsListPage as one of its declarations.

**Comment by Rickem** [comment]
I've tried to import NgxPaginationModule here as well

`import { NgModule } from '@angular/core';
import { IonicPageModule } from 'ionic-angular';
import { WordsListPage } from './words-list';

@NgModule({
  declarations: [
    WordsListPage,
  ],
  imports: [
    IonicPageModule.forChild(WordsListPage),
  ],
})
export class WordsListPageModule {}

`

**Comment by michaelbromley** [comment]
Okay, importing the NgxPaginationModule into the above NgModule should solve the issue. But since you say you already tried it and it didn't work, I'm not sure what else to suggest. 

By the way, to format code blocks, use three back ticks followed by the language: ` ```TypeScript ` and then close with another three back ticks. I took the liberty of doing this for your last two comments.

**Comment by Rickem** [comment]
Importing the NgxPaginationModule into the NgModule generates another error message. 

**Unexpected module 'NgxPaginationModule' declared by the module 'WordsListPageModule'. Please add a @Pipe/@Directive/@Component annotation.**

This probably means that I'm making progress. Anyway, I don't want to take much of your time. I'll keep trying to make it work. I'll inform you of the outcomes.
I really appreciate your help.

**Comment by michaelbromley** [comment]
Make sure you put it in the "imports" array, not the "declarations" array. No problem re. time. I'm just sitting here, chilling out on the couch. Probably gonna watch a Stranger Things episode later. No stress 😄

**Comment by Rickem** [comment]
Wow that actually kinda worked. I've got no error message but the data isn't display in the words-list.html.

**Comment by michaelbromley** [comment]
Cool! Okay, sounds like the original issue is fixed then.

Now I guess you just have to roll up your sleeves and get busy debugging! I'm gonna sign off now cos the kettle has boiled and I'm about to be presented with a cup of tea (I'm English) to enhance my Netflix viewing pleasure. Good luck!

**Comment by Rickem** [comment]
Thanks. Enjoy your cup of tea and Netflix.
