### ISSUE TITLE
The pipe 'paginate' could not be found

### ISSUE THREAD

**Issue by AbdurRehman91** [michaelbromley/ngx-pagination#216]
**Angular version**:
4.4.6
**ngx-pagination version**:
0.1.0

**Description of issue**:
Uncaught (in promise): Error: Template parse errors:
The pipe 'paginate' could not be found ("
**Steps to reproduce**:
I have also included the Ng2PaginationModule in the specific module in which i am using the pagination but it is still giving me this error

**Expected result**:
The pagination issue should be solved
**Actual result**:
The error is being generated
**Demo**: (if possible, edit [this StackBlitz demo](https://stackblitz.com/edit/angular-e1f9hq) and paste the link to your fork)

Any relevant code:
```TypeScript
import { Component, OnInit } from '@angular/core';
import {ActivatedRoute, Router} from "@angular/router";
import {BrowserModule} from '@angular/platform-browser';
import { Ng2PaginationModule } from 'ng2-pagination';`
```

thanks

**Comment by michaelbromley** [comment]
Hi,

You are using an extremely outdated version of the lib (0.1.0) from over a year and a half ago. It is not compatible with Angular 4. Please update to the latest version (`npm install ngx-pagination`) - 3.0.3 at this time of writing - and report back.
