### ISSUE TITLE
Can't execute code after the new page is loaded

### ISSUE THREAD

**Issue by NafaaAzaiez** [michaelbromley/ngx-pagination#219]
**Angular version**: 5

**ngx-pagination version**: 3.0.3

**Description of issue**: I have 10 canvas on which I draw some shapes in the ngAfterViewInit(), when i use ngx-pagination to paginate those canvas each on a page, when I change the page, the canvas is empty as if the dom is re-loaded and the code to draw is not executed. I tried to put this code in a function called on the pageChange event but it doesnt work either, I think the code is executed before the page is loaded, at the time of click, at that moment there is no canvas to draw on.  

I looked at the source code of ngx-pagination, couldn't find an event to capture that is fired after the new page is loaded.

**Comment by michaelbromley** [comment]
Hi,

ngx-pagination does not do anything special with regards to the component lifecycle of items in the list. It just uses a pipe (`paginate`) to split up the collection array. Everything else is handled by the Angular ngFor implementation.

> I looked at the source code of ngx-pagination, couldn't find an event to capture that is fired after the new page is loaded.

There is no such event. ngx-pagination has no knowledge of this. When you change pages, all it does is slice your collection array at a different place and then hand over the results to ngFor.

If you are able to put together a minimal reproduction of your issue, I could take a look and try to help further. You can use [this StackBlitz demo](https://stackblitz.com/edit/angular-e1f9hq) as a starting point.

**Comment by NafaaAzaiez** [comment]
Hi,

Thank you for this explanation, it's does make more sense now. My canvas is being rendered empty because it is recreated everytime I change the page. This is done by the ngFor not the pagination module, everytime ngfor recreate the page using the collection it got from the pagination.

I will be waiting for the ngFor to finish (using the "last" attribute) then run my js code to draw on canvas.

Thank you again, I hope thiw will help someone else.
Sincerely

**Comment by michaelbromley** [comment]
Good, thanks for sharing your solution 👍
