### ISSUE TITLE
Can i change/remove the "next"or "prev" arrow ?

### ISSUE THREAD

**Issue by arzazahrian** [michaelbromley/ngx-pagination#220]
**Angular version**: 5

**ngx-pagination version**: 3.0.3
 i want to change the content that show "prev" and "next" at the control ?

**Comment by michaelbromley** [comment]
You mean you want to change the text of the label? If so, there are two inputs you can set, `previousLabel` and `nextLabel`. This is covered [here in the docs](https://github.com/michaelbromley/ngx-pagination/tree/841bd148b5870a9c9df6a5dcbf77ca9e26dc1c35#paginationcontrolscomponent)

**Comment by mapsgeek** [comment]
what about that very small double arrow next to the words " next and previous " ?

**Comment by mapsgeek** [comment]
WHY ?!! just give me a reason that makes you this ?!!!
`.ngx-pagination .pagination-previous a::before,
.ngx-pagination .pagination-previous.disabled::before { 
  content: '«';
  display: inline-block;
  margin-right: 0.5rem; }`

**Comment by TheBearSO** [comment]
Hi @mapsgeek you can do this to remove it for now:

```
.ngx-pagination .pagination-previous a::before,
.ngx-pagination .pagination-previous.disabled::before,
.ngx-pagination .pagination-next a::after,
.ngx-pagination .pagination-next.disabled::after { 
  content: '' !important; 
}
```

_About the problem, yes maybe it would be better that these arrows aren't inserted from css and when you override the labels these arrows disappear too. 
But anyways, this is an open source project, you are able to make a PR or propose a different or better solution._ 

Thanks

**Comment by TheBearSO** [comment]
@michaelbromley About this issue, what do you say if we use `[innerHTML]` instead pseudo selectors like ::after and ::before. 
I'm talking about this part: https://github.com/michaelbromley/ngx-pagination/blob/master/src/template.ts#L17

I can do something to improve the icons overriding. I'm  thinking in two ways for now:

- One way could be add a new properties in the pagination control like `previousIcon` and `nextIcon`.
- Another way could be that `previousLabel` and `nextLabel` support html and the user can override it as he want. 

_I don't know if these could have breaking changes with previous versions (I don't think so) and obviously if you have a better way, tell me._

**Comment by michaelbromley** [comment]
@TheBearSO Thanks for taking this on. Here are my thoughts on what you suggested:

I would avoid using `innerHTML`, because I think it would get really messy to provide HTML strings as inputs to the component. Also there are security risks associated with binding to innerHTML [[see docs](https://angular.io/api/platform-browser/DomSanitizer#security-risk) - probably not too much to worry about in this case, but worth mentioning.

If we used `previousIcon` properties, then how do we specify the icons? Do we limit it to unicode characters? What is someone wants to use an icon font or SVG? 

We might be able to use a supplied `TemplateRef` for the icons, which would allow the user to specify the labels in any way he or she sees fit. In fact, this could be done not just for the prev / next links, but for all pages too. Worth exploring.

**Comment by TheBearSO** [comment]
Thanks for the awnser @michaelbromley. 
Ok, I will explore deeply and find the best option.  The templateRef idea sounds good, if I can do something I will show you.

**Comment by nhducseuit** [comment]
You can modify those icons into different icons by overriding the css:
`.ngx-pagination .pagination-previous a::before, .ngx-pagination .pagination-previous.disabled::before { font-family: 'Material Icons';
        content: 'keyboard_arrow_right';
        vertical-align: middle;
        display: inline; }`

Noted that you have to override `display: inline` as well

**Comment by lakhwindergill** [comment]
@TheBearSO I tried the solution you mentioned above. It's not working. Did you do anything else apart from the CSS change?
.ngx-pagination .pagination-previous a::before,
.ngx-pagination .pagination-previous.disabled::before,
.ngx-pagination .pagination-next a::after,
.ngx-pagination .pagination-next.disabled::after { 
  content: '' !important; 
}

**Comment by BHUWANESHWAR2210** [comment]
Here I'm customizing the pagination controls by overriding the CSS to use Material Icons. Based on the code snippet you provided, here's how you can modify the icons and ensure that the display properties are correctly set.

Try this:

.ngx-pagination .pagination-previous a::before, 
.ngx-pagination .pagination-previous.disabled::before, 
.ngx-pagination .pagination-previous.disabled a::before {
    font-family: 'Material Icons' !important;
    content: '\2039' !important; 
    vertical-align: middle !important;
    display: inline !important;
}
.ngx-pagination .pagination-previous a::after,
.ngx-pagination .pagination-previous.disabled a::after {
    content: '' !important; 
}

.ngx-pagination .pagination-next a::before, 
.ngx-pagination .pagination-next.disabled::before, 
.ngx-pagination .pagination-next.disabled a::before {
    font-family: 'Material Icons' !important;
    content: '\203A' !important; 
    vertical-align: middle !important;
    display: inline !important;
}
.ngx-pagination .pagination-next a::after,
.ngx-pagination .pagination-next.disabled a::after {
    content: '' !important; 
}

.ngx-pagination .pagination-next.disabled::after,
.ngx-pagination .pagination-previous.disabled::after {
    content: '' !important;
}

.ngx-pagination .pagination-next a,
.ngx-pagination .pagination-previous a {
    font-family: 'Material Icons' !important;
    content: '' !important;
}
