### ISSUE TITLE
Duplicating Pagination Controls element when using BrowserAnimationsModule

### ISSUE THREAD

**Issue by AnYoung627** [michaelbromley/ngx-pagination#221]
**Angular version**:
4.3.6
**ngx-pagination version**:
3.0.3
**Description of issue**:
I uncovered this while using your control in conjunction with the Angular 'BrowserAnimationsModule' from @angular/platform-browser/animations.

When an item in the collection does not exist (i.e. is undefined) and an attempt is made to access and display a property of said object, the pagination control duplicates itself, if the corrupt/missing item is on a different page than the page initially loaded. (see demo)

**Steps to reproduce**:
1. import the BrowserAnimationsModule into the app.module.ts file
2. Create a basic pagination control (such as the basic example) that has a collection of objects, enough to fill 1.5+ pages, with the first page (default of 10 per page) being proper objects, with one property, such as { 'name' : 'testing' }.
3. Add a corrupt/undefined object to the collection, that would be displayed on the second page (say, index 12)

4. in the template, display the 'name' property in a list managed by the pagination control.
5. Run your project
6. click '2' or 'next' on your control

**Expected result**:
The first page of results should display correctly, and the page with the error should display all items without an error correctly, displaying the undefined/corrupt item as a blank item.
Pagination control should display as normal, without duplicating.

**Actual result**:
The first page of results should properly display the 'name' field of the items in your collection, and the pagination control should appear at the bottom of the screen. Upon clicking the control, to navigate to the page with the corrupt data (in the demo this is only page 2), the control duplicates, and the 'old' control buttons are unbound from their click actions. 

**Demo**: https://stackblitz.com/edit/angular-lqaptf

**Comment by michaelbromley** [comment]
This is bizarre. Thanks for the detailed report, I'll take a deeper look into what's going on when I have some time, maybe tomorrow.

**Comment by michaelbromley** [comment]
Okay, I looked into this further. I don't think it necessarily has to do with this module. Rather, your code is generating a runtime error because you are trying to access a property of `undefined` in your template. If you add a safe navigation operator to your template, everything works as expected:

```HTML
{{ item?.name }}
```
