### ISSUE TITLE
pagination options from object

### ISSUE THREAD

**Issue by JaroslavPrt** [michaelbromley/ngx-pagination#222]
have service method that returns info about amount of users (current page, total, users per page etc)
pagination options get from object, but paginate pipe and pagination-controls not working by this way

```TypeScript
        this.usersService.getUsers(this.projectId, pageNumber).subscribe(users => {
            this.paginateConfig.totalItems = this.usersService.numberOfPages;
            this.paginateConfig.itemsPerPage = this.usersService.usersPerPage;
            this.asyncUsers = Observable.of(users).map(u => u);
        });

        <tr *ngFor="let user of asyncUsers | async | paginate: paginateConfig">
        <pagination-controls id="paginateConfig.id" (pageChange)="goToPage($event)">
        </pagination-controls>

```

there are 100 per page and around 20 pages, but get this result
![pag_res](https://user-images.githubusercontent.com/11339544/34485002-043cb690-efd1-11e7-961a-707709f8c3c3.png)

p/s/  service filtering, mutating, ...  data from api then create and return collection of users, it can't be changed

**Comment by HristoKolev** [comment]
An exceptionally well defined question.

**Comment by michaelbromley** [comment]
Hi,

This line stands out to me as a possible error:

```TypeScript
this.paginateConfig.totalItems = this.usersService.numberOfPages;
```

Since `totalItems` should be the number of items/rows/users in the entire dataset, whereas `numberOfPages` suggests `items / itemsPerPage`.

> p/s/ service filtering, mutating, ... data from api then create and return collection of users, it can't be changed

I don't understand what you mean by this.

**Comment by JaroslavPrt** [comment]
thx, I'll revise code and try it 
i mean i can't modify service
