### ISSUE TITLE
boundaryLinks="true"  not working

### ISSUE THREAD

**Issue by AayushShahu** [michaelbromley/ngx-pagination#223]
<pagination-controls 
        (pageChange)="p = $event"
        boundaryLinks= "true"
        directionLinks="true"
        autoHide="true"
        previousLabel="Previous"
        nextLabel="Next"
      >
      </pagination-controls>

**Comment by michaelbromley** [comment]
Hi,

Can you describe the issue? "Not working" is a bit too vague. 

Also, please include a reproduction of the issue so I can debug it. Edit [this StackBlitz demo](https://stackblitz.com/edit/angular-e1f9hq) and paste the link to your fork.

If you can provide this, I'll be able to take a look.

**Comment by ChaudhryAtif** [comment]
@michaelbromley Looks like boundaryLinks is no longer documented, and is not a property of pagination controls anymore. Any idea why?

**Comment by michaelbromley** [comment]
@ChaudhryAtif actually, boundaryLinks was never implemented in this library. Here's a brief mention of why not: https://github.com/michaelbromley/ngx-pagination/issues/103#issuecomment-262464798
