### ISSUE TITLE
Page change event is called 2-3 times 

### ISSUE THREAD

**Issue by abhilashrathod** [michaelbromley/ngx-pagination#224]
**Angular**: 4.4.6

**ngx-pagination**: 3.0.3

**Description**: pageChange event is called 3 times 

**Reproduction steps**: followed the tutorial of the basic demo from your site, it works best. However, I have worked with this package previously but this has happened the first time. Please review the code

**Expected result**: Should be called only one time

**Actual result**: It's called 3 times 

**Code:**

*HTML Code*
```
 <div class="row mb-30" *ngFor="let medicine of medications | async | paginate: { id: 'server', itemsPerPage: filterObject.limit, currentPage: page, totalItems: total}">
<!-- repeat body --> 
</div>
<div class="row">
     <div class="col-12">
            <pagination-controls (pageChange)="getPage($event)" id="server"></pagination-controls>
     </div>
</div>
```
*Typescript Code*

```
medications: Observable<any>;
  filterObject: any = {
    limit: 2,
    offset: 0,
    filter: 'name',
    filter_text: ''
  };
  total: number;
  page: any;


ngOnInit() {
    this.getPage(1);
  }

  getPage(page: number) {
    console.group('Page called');
    this.filterObject.offset = this.filterObject.limit * (page - 1);
    this.medications = this._admin.getMedicines(this.filterObject)
        .do(res => {
          this.total = res['total_count'];
          this.page = page;
        })
        .map(res => res['data'])
  }
```

**Comment by Liahus3003** [comment]
Did you fix this issue ? I am facing this same scenario now

**Comment by abhilashrathod** [comment]
@Liahus3003 The issue was from server side. The problem was that the ```total_count``` needed for the pagination was returned same everytime.

**Comment by YJChan** [comment]
Hi, I'm facing the same issue here. Can you elaborate more 
"**The problem was that the total_count needed for the pagination was returned same everytime.**" .
Let's say my db has 100 records in total, my page size is 10, then I will have ten pages. However, to show 10 page in the pagination I need to display, it required me to return the total count (100). No matter which page I'm at I will always get 100.
