### ISSUE TITLE
Serial ID not incrementing on rows

### ISSUE THREAD

**Issue by bhagatshubham1994** [michaelbromley/ngx-pagination#227]
Hi Michael,

I am using ng2-pagination in my angular 2 application now I want to show serial ID on rows increment to all the rows from 1 to 49th row. I write some code but it only shows 1 to 10 number and it loads again from 1 to 10 number when I go to next page and so on.
my table show 10 records per page.

my code.
```HTML
<tr *ngFor="let shipment of finalShipmentList | paginate:{ itemsPerPage:10, currentPage: p }; let i = index;">
<td [routerLink]= "['/truckDetails',shipment.truckNumber,shipment.ShipmentID]">{{ i +1 }}</td>
```

In ngx-pagination `{{ (config.currentPage - 1) * config.itemsPerPage + i +1 }}` is not working in my case as I have not used config. Instead of " paginate: config " I am using " paginate:{ itemsPerPage:10, currentPage: p " Is there a way to access currentPage & itemsPerPage inside {{ }} as I want them to make the above formula work. Any help would be greatly appreciated as I am stuck in this issue for quite long. Thanks in advance :)

**Comment by michaelbromley** [comment]
Config is just an object containing the properties `itemsPerPage` and `currentPage`. Since you are using an object-literal approach instead, you can just fill in the variables that you use. I.e.:

```
{{ (p - 1) * 10 + i +1 }}
```

**Comment by bhagatshubham1994** [comment]
Thanks a lot Michael for instant reply, its working now. 

One more thing I wanted to ask can we apply some CSS to the slider **{ << Previous   1 2 3 4 5    Next>>}**
or is there any way to bring this Page Changing bar at the center.

**Comment by michaelbromley** [comment]
Glad you got it fixed.

For styling, see https://github.com/michaelbromley/ngx-pagination#styling

To center it, why not just wrap it in a `<div>` with a style of `text-align: center;`? That should work.
