### ISSUE TITLE
Remove page numbers 

### ISSUE THREAD

**Issue by DelaneyGalvanize** [michaelbromley/ngx-pagination#230]
Hi, thanks for contributing!

Is there a way to not show the page numbers and simply just show 'next' and 'previous'?

=======

**Angular version**:

**ngx-pagination version**:

**Description of issue**:

**Steps to reproduce**:

**Expected result**:

**Actual result**:

**Demo**: (if possible, edit [this StackBlitz demo](https://stackblitz.com/edit/angular-e1f9hq) and paste the link to your fork)

Any relevant code:
```

```

**Comment by TheBearSO** [comment]
Hi @DelaneyGalvanize, In fact I saw the docs and there isn't any directive property to hide the page numbers, but if you see style part, you are able add a custom class to wrap your pagination component, so  hide them is just one line of css:

**CSS**
```
.hide-page-numbers /deep/ .ngx-pagination li:not(.pagination-previous):not(.pagination-next) {
  display: none;
}
```
**HTML**
```
<pagination-controls class="hide-page-numbers"></pagination-controls>
```

Please, see [your updated StackBlitz](https://stackblitz.com/edit/angular-4drre9)

**Comment by michaelbromley** [comment]
What @TheBearSO suggests is one way to do it (the simplest way). Ps I love it when other people answer issues on my repos! Thanks!

Another way to do it would be to create your own template which simply omits the page numbers:

```HTML
    <pagination-template #api="paginationApi" (pageChange)="p = $event">
        <div class="pagination-previous" [class.disabled]="api.isFirstPage()">
            <a (click)="api.previous()"> Previous </a>
        </div>
        <div class="pagination-next" [class.disabled]="api.isLastPage()">
            <a (click)="api.next()"> Next </a>
        </div>
    </pagination-template>
```

See a [working demo here](https://stackblitz.com/edit/angular-adm5um)
