### ISSUE TITLE
Pagination controls not keyboard accessible

### ISSUE THREAD

**Issue by jessemorton** [michaelbromley/ngx-pagination#231]
**Angular version**: 5.1.0

**ngx-pagination version**: 3.0.3

**Description of issue**: Pagination controls can be clicked via mouse but not clicked via tabbing and pressing Enter  on keyboard. It's great you have aria labels on the controls, but I think not having the anchors contain a `href="#"` and `e.preventDefault()` type of setup is limiting the accessibility for assistive technology, but also is just less user friendly for heavy keyboard users. (I totally get that this is maintained in your spare time and that assistive technology considerations aren't to be taken for granted for OSS, but also figured this is a pretty easy fix benefitting others as well.)

**Steps to reproduce**: Press Tab key repeatedly while viewing page w/pagination.

**Expected result**: Should cause the pagination controls to become activated sequentially. Pressing Enter while having a pagination control activated should give same result as clicking the control w/a mouse.

**Actual result**: Notice that the pagination controls never become available to click via Enter key

P.S. thanks for this project!

**Comment by michaelbromley** [comment]
Hi,

This is a good point, and should not be difficult to implement. Perhaps just adding a `tabindex` property to each button will fix this. I'll look into it.

P.S. you are welcome, and I appreciate your respectful approach to reporting this issue 👍

**Comment by jessemorton** [comment]
Thanks @bernhardriegler @michaelbromley!
