### ISSUE TITLE
Configure page start index [Request]

### ISSUE THREAD

**Issue by ChaudhryAtif** [michaelbromley/ngx-pagination#234]
**Angular version**: 5.2.4

**ngx-pagination version**: 3.0.3

**Description of issue**: When using this libraries to paginate using JPA, it has 0-based page index, and calculates everything off of that. This library uses 1-based (like most libraries). It causes issued with getting the correct page data, and shows the wrong current page in pagination control.

**Comment by michaelbromley** [comment]
I am not familiar with JPA, but can't you just add a 1 to the 0-based value that it uses?

If it's more complex than than, please include some code so I can better understand the issue.

**Comment by ChaudhryAtif** [comment]
I can't change the index of backend, so if anything, I'll need to subtract 1 before sending it to the server. But how do I get the correct page to show?

**Comment by michaelbromley** [comment]
I'm not sure if I am missing something, but it sounds like you already have the solution there - subtract 1 before sending to the server. Like I said, it's much easier if you share a bit of code so I know exactly what the challenge is. But the basic idea is:

```TypeScript
pageChange(pageNumber: number) {
  this.api.getPage(pageNumber - 1)
    .subscribe(result => this.items = result.data);
}
```

**Comment by ChaudhryAtif** [comment]
I needed to make more changes since I was showing the item count and all, but I was able to resolve it some some extra calculations. Thank you for the swift response.
