### ISSUE TITLE
 <tr *ngFor="let user of users; let i = index|paginate:{ itemsPerPage:10, currentPage:p}">

### ISSUE THREAD

**Issue by Mukesh1412** [michaelbromley/ngx-pagination#237]
Parser Error: Unexpected token |, expected identifier, keyword, or string at column 33 in [let user of users; let i = index|paginate:{ itemsPerPage:10, currentPage:p}]

**Comment by TheBearSO** [comment]
Hi @Mukesh1412 thanks for you upload an issue. 
To fix it, you should add the `let i = index` after the pagination pipe.

`*ngFor="let item of collection | paginate: { itemsPerPage: 10, currentPage: p }; let i = index"`

Check a demo with your issue: https://stackblitz.com/edit/angular-rjtamu?file=app/app.component.html

**Comment by TheBearSO** [comment]
@michaelbromley What do you say if I add this example to [FAQ](https://github.com/michaelbromley/ngx-pagination#faq) section. Do you think is relevant? Maybe is a common mistake declare the index of the ngFor in a wrong way with the pagination.

**Comment by TheBearSO** [comment]
Hi @Mukesh1412 thanks for upload the issue.
To fix it, you should declare the `let i = index` after the pagination pipe:

`*ngFor="let item of collection | paginate: { itemsPerPage: 10, currentPage: p }; let i = index"`

Check this [stackblitz](https://stackblitz.com/edit/angular-rjtamu?file=app/app.component.html) live demo

**Comment by TheBearSO** [comment]
@michaelbromley  What do you say if I add this example to [FAQ](https://github.com/michaelbromley/ngx-pagination#faq) section. Do you think is relevant? Maybe is a common mistake declare the index of the ngFor in a wrong way with the pagination pipe.

**Comment by michaelbromley** [comment]
@TheBearSO Sure, that would be helpful!

**Comment by mumarqayyum051** [comment]
With this solution, the problem is still the same. After every render, the index resets back to 0 and it only renders the index count between 0-9.

**Comment by mumarqayyum051** [comment]
> Hi @Mukesh1412 thanks for upload the issue.
> To fix it, you should declare the `let i = index` after the pagination pipe:
> 
> `*ngFor="let item of collection | paginate: { itemsPerPage: 10, currentPage: p }; let i = index"`
> 
> Check this [stackblitz](https://stackblitz.com/edit/angular-rjtamu?file=app/app.component.html) live demo

With this solution, the problem is still the same. After every render, the index resets back to 0 and it only renders the index count between 0-9.

**Comment by imasfandyarali** [comment]
Hi there. I'm still having difficulty with this. the problem is still the same. After every render, the index resets back to 0 and it only renders the index count between 0-9. I'm an angular starter. Can someone help please?

**Comment by michaelbromley** [comment]
Check out this part: https://github.com/michaelbromley/ngx-pagination#how-do-i-get-the-absolute-index-of-a-list-item
