### ISSUE TITLE
Question: Is it possible to do a `p.next()` from within a component.ts?

### ISSUE THREAD

**Issue by narzero** [michaelbromley/ngx-pagination#242]
@michaelbromley thank you for this awesome library!

What I would like to do is map the keyboard arrows "left" and "right" to the `p.previous()` and `p.next()` so the visitor can use the keyboard arrows to paginate.

Is this possible? I can't seem to access the `PaginationControlsDirective` from within the component.ts file.

**Comment by michaelbromley** [comment]
Hi, this should be possible. What have you tried so far?

First idea that comes to mind is using a `@ViewChild(PaginationControlsDirective)` decorator to get hold of the directive.

**Comment by narzero** [comment]
@michaelbromley `@ViewChild(PaginationControlsDirective` works, thank you!
