### ISSUE TITLE
Cannot read property 'OnPush' of undefined

### ISSUE THREAD

**Issue by skolli853780** [michaelbromley/ngx-pagination#243]
Hello,

I am trying to use ngx-pagination with Angular 4.. everything works fine, except that I am seeing an error message in the console..

ngx-pagination.umd.js?1522763036168:273 Uncaught TypeError: Cannot read property 'OnPush' of undefined
    at ngx-pagination.umd.js?1522763036168:273
    at ngx-pagination.umd.js?1522763036168:292
    at PaginationService.defaultId (ngx-pagination.umd.js?1522763036168:4)
    at ngx-pagination.umd.js?1522763036168:5

clicking on the error, points to below lines of code..

    PaginationControlsComponent.decorators = [
        { type: core.Component, args: [{
                    selector: 'pagination-controls',
                    template: DEFAULT_TEMPLATE,
                    styles: [DEFAULT_STYLES],
                    changeDetection: core.ChangeDetectionStrategy.OnPush,
                    encapsulation: core.ViewEncapsulation.None
                },] },
    ];

we are using https://github.com/mgechev/angular-seed to build our application..

In my project.config file, I have added ngx-pagination.umd.js file

    // Add `NPM` third-party libraries to be injected/bundled.
    this.NPM_DEPENDENCIES = [
      ...this.NPM_DEPENDENCIES,
      {src: 'ngx-pagination/dist/ngx-pagination.umd.js', inject: 'libs'},
    // inject into css section
  ];

please advise 

Thanks
SK

**Comment by michaelbromley** [comment]
Hi,

It looks like you are loading the module with SystemJS. I don't have a lot of experience with it, but perhaps you shouldn't be using the UMD bundle. What happens if you just us the `ngx-pagination.js` file instead?

**Comment by skolli853780** [comment]
Thank you for your quick response.. we are using SystemJS.. if I use ngx-pagination.. I am getting below error..

localhost/:153 TypeError: Unable to dynamically transpile ES module
   A loader plugin needs to be configured via `SystemJS.config({ transpiler: 'transpiler-module' })`.
    at transpile (http://localhost:5555/node_modules/systemjs/dist/system.src.js?1522938080837:3689:11)

with UMD, functionality is working fine.. it's just that I am getting error in console.. please advise

Thanks
SK

**Comment by michaelbromley** [comment]
Hi,

I'm afraid I've not got a ready solution to that. If you are somehow able to put together a simple reproduction I may be able to dig in further and offer a bit more help.

**Comment by skolli853780** [comment]
error is at line  PaginationControlsComponent.decorators = [
    { type: core.Component, args: [{
                selector: 'pagination-controls',
                template: DEFAULT_TEMPLATE,
                styles: [DEFAULT_STYLES],
                changeDetection: core.ChangeDetectionStrategy.OnPush,
                encapsulation: core.ViewEncapsulation.None
            },] },
];  Cannot read property 'OnPush' of undefined.. Do I need to define ChangeDetectionStrategy? I think it is complaining about core.ChangeDetectionStrategy undefined and cannot read property OnPush of undefined..

**Comment by michaelbromley** [comment]
`ChangeDetectionStrategy` is part of Angular itself, so you should never need to define it yourself. If you set a breakpoint at this exception, check the value of `core` - it seems strange that some of its members (e.g. `Component`) are defined but others not. No idea why this would be.

**Comment by skolli853780** [comment]
I have put a breakpoint at Paginationcontrolscomponents and I see it as undefined, also for PaginationControlsDirective

PaginationControlsComponent:undefined
PaginationControlsDirective:undefined
PaginationService:ƒ PaginationService()
common:undefined
core:{version: "2.5.3", inspectSource: ƒ, prototype: {…}, Object: {…}, JSON: {…}, …}

**Comment by skolli853780** [comment]
At the code 
    PaginationService.prototype.defaultId = function () { return this.DEFAULT_ID; };
I am getting error PaginationService is not defined..

message:"PaginationService is not defined" 
stack: "ReferenceError: PaginationService is not defined↵    at eval (eval at PaginationService.defaultId (http://localhost:5555/node_modules/ngx-pagination/dist/ngx-pagination.umd.js?1523899004056:4:3), <anonymous>:1:1)↵    at PaginationService.defaultId (http://localhost:5555/node_modules/ngx-pagination/dist/ngx-pagination.umd.js?1523899004056:4:3)↵    at http://localhost:5555/node_modules/ngx-pagination/dist/ngx-pagination.umd.js?1523899004056:5:2"

**Comment by chuanlin2018** [comment]
Hello skolli853780, has this problem been resolved? I am having the same issue...
