### ISSUE TITLE
How to stay on current page

### ISSUE THREAD

**Issue by DanieleAndrade** [michaelbromley/ngx-pagination#244]
**Angular version**: 4.2.4

**ngx-pagination version**: 3.0.3

**Description of issue**:
How to stay on current page when the page is reloaded? Currently it always reset to the first page.

**Comment by DanieleAndrade** [comment]
Thank you @michaelbromley :+1:

**Comment by michaelbromley** [comment]
You're very welcome. I assume by your lack of follow up that this was enough for you to resolve the issue, so I'll close. If not and you need further help, feel free to comment further 👍
