### ISSUE TITLE
Installing ngx-pagination deleting cuint module

### ISSUE THREAD

**Issue by aramiscubillo** [michaelbromley/ngx-pagination#246]
So my project was working fine and yesterday I decided to install **ngx-pagination**.
After that, every time I did **npm start** it showed me this error:

```
ERROR in ./node_modules/css-loader?{"sourceMap":false,"import":false}!./node_mod
ules/postcss-loader/lib?{"ident":"postcss","sourceMap":false}!./node_modules/fon
t-awesome/css/font-awesome.css
Module build failed: Error: Cannot find module 'cuint'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Aramis\Documents\1o1WVC\frontend\src\main\fr
ontend\node_modules\xxhashjs\lib\xxhash.js:7:30)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Aramis\Documents\1o1WVC\frontend\src\main\fr
ontend\node_modules\xxhashjs\lib\index.js:2:7)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
 @ ./node_modules/font-awesome/css/font-awesome.css 4:14-124
 @ multi ./src/styles.css ./src/lg-styles.css ./src/md-styles.css ./src/sm-style
s.css ./src/xs-styles.css ./node_modules/font-awesome/css/font-awesome.css

webpack: Failed to compile.
```

After some digging around, I realized that every time I installed **ngx-pagination**, for some reason, it deletes the **cuint module** located on **node_modeles** and that's why the error is happening.

Is there any reason on why this is happening??

=======

**Angular version**:
```
<!--
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / ? \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/

Angular CLI: 1.6.4
Node: 6.11.0
OS: win32 x64
Angular: 5.2.0
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.6.4
@angular-devkit/build-optimizer: 0.0.38
@angular-devkit/core: 0.0.25
@angular-devkit/schematics: 0.0.48
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.4
@schematics/angular: 0.1.13
@schematics/schematics: 0.0.13
typescript: 2.5.3
webpack: 3.10.0

node --version
v6.11.0

npm --version
5.0.3

Windows 8.1

ngx-pagination version:  "ngx-pagination": "^3.1.0",
```

**Description of issue**:
**npm install ngx-pagination --save** deletes **cuint module** located on **node_modeles** and project won't build

**Steps to reproduce**:
1-npm install ngx-pagination --save
2-Check if cuint module folder was deleted
3-npm start

**Comment by TheBearSO** [comment]
Hi @aramiscubillo, thanks for uploading an issue. 
Where and how is installed the `cuint module`? Is really weird that `npm install` command remove a package. There is something more. 

If you install any other third party lib, that package isn't removed? Have you tried that?

**Comment by aramiscubillo** [comment]
I fixed the problem. I think is a bug related to npm install, for some reason it deletes other packages on install.
Fix it by updating node to latest version:  8.11.1 and updating npm to 5.6.0

**Comment by michaelbromley** [comment]
Glad you got it resolved. I have run into weird issues with npm occasionally too like this. My conclusion is to start to transition to Yarn, which so far seems to be free from this kind of thing.
