### ISSUE TITLE
Problems compiling under fullTemplateTypeCheck flag

### ISSUE THREAD

**Issue by rafaelss95** [michaelbromley/ngx-pagination#247]
**Angular version**:

```
    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/

Angular CLI: 1.7.3
Node: 9.8.0
OS: darwin x64
Angular: 5.2.9
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

@angular/cli: 1.7.3
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.3.2
@angular-devkit/schematics: 0.3.2
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.2
@schematics/angular: 0.3.2
@schematics/package-update: 0.3.2
typescript: 2.6.2
webpack: 3.11.0
```

**ngx-pagination version**:
3.1.0

**Description of issue**:

**Steps to reproduce**:
Enable `fullTemplateTypeCheck` under `angularCompilerOptions` in `tsconfig.app.json`:

```
{
  "angularCompilerOptions": {
    "fullTemplateTypeCheck": true
  }
}
```

**Expected result**:
Compiles without any errors.

**Actual result**:
> Argument of type 'ReadonlyArray\<AType\>' is not assignable to parameter of type 'any[]'.
>   Property 'push' is missing in type 'ReadonlyArray\<AType\>'.

Any relevant code:
```ts
@Component({
  preserveWhitespaces: false,
  selector: '...',
  styleUrls: ['./...'],
  templateUrl: './...'
})
export class TestComponent {
  items: ReadonlyArray<AType>;
}
```

```html
<div *ngFor="let item of items | paginate: paginationConfig">
  {{ item | json }}
</div>
```

**Comment by TheBearSO** [comment]
Hello @rafaelss95 thanks for uploading the issue. 

Unfortunately I don't have too much experience with angular-cli config (I always use plain/custom webpack config), so is difficult to me reproduce the problem. 
It would be great if you use stackblitz or at least share a github repo to see the issue live. Here I've tried something [https://stackblitz.com/edit/angular-m3d9bt?file=app/app.component.ts](https://stackblitz.com/edit/angular-m3d9bt?file=app/app.component.ts) (fork this and try to reproduce your problem if you can).

If is impossible to reproduce give me some days and I will try it at home. Maybe @michaelbromley has a better idea of what is happen.

**Comment by rafaelss95** [comment]
Hey @TheBearSO, it was a simple problem, please take a look on PR.

**Comment by michaelbromley** [comment]
@rafaelss95 thanks, the PR looks good. When I get a bit of time this coming week I'll include it in a new release.
