### ISSUE TITLE
How do I get all pages instead of few in page.label

### ISSUE THREAD

**Issue by sandeesaripalli** [michaelbromley/ngx-pagination#251]
Hi,
I am trying to use custom template and as per my requirement, I need the page numbers in a dropdown. When I try to put in dropdown I get some page numbers instead of all. On checking code, seems like you are truncating the numbers which shows up while moving to next page. May I know if is there a way to get all page numbers?

Example : if there are 8 pages then I see 1,2,3,4,5 ... ,8 but I want it as 1,2,3,4,5,6,7,8

Thanks.

**Comment by michaelbromley** [comment]
Hi,

You can get all the numbers by setting the `maxSize` input to a very large number.

**Comment by sandeesaripalli** [comment]
Thanks a lot.
