### ISSUE TITLE
Can't install ngx-pagination on angular5

### ISSUE THREAD

**Issue by zorikz** [michaelbromley/ngx-pagination#253]
npm ERR! path C:\***\node_modules\.staging\domino-bc96a811\test\fixture\jquery-1.9.1.js
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall unlink
npm ERR! Error: EPERM: operation not permitted, unlink 'C:\***\node_modules\.staging\domino-bc96a811\test\fixture\jquery-1.9.1.js'
npm ERR!  { Error: EPERM: operation not permitted, unlink 'C:\***\node_modules\.staging\domino-bc96a811\test\fixture\jquery-1.9.1.js'
npm ERR!   cause:
npm ERR!    { Error: EPERM: operation not permitted, unlink 'C:\***\node_modules\.staging\domino-bc96a811\test\fixture\jquery-1.9.1.js'
npm ERR!      errno: -4048,
npm ERR!      code: 'EPERM',
npm ERR!      syscall: 'unlink',
npm ERR!      path: 'C:\\***\\node_modules\\.staging\\domino-bc96a811\\test\\fixture\\jquery-1.9.1.js' },
npm ERR!   stack: 'Error: EPERM: operation not permitted, unlink \'C:\\***\\node_modules\\.staging\\domino-bc96a811\\test\\fixture\\jquery-1.9.1.js\'',
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'unlink',
npm ERR!   path: 'C:\\***\\.staging\\domino-bc96a811\\test\\fixture\\jquery-1.9.1.js',
npm ERR!   parent: '***' }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It's possible that the file was already in use (by a text editor or antivirus),
npm ERR! or that you lack permissions to access it.
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator (though this is not recommended).

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\username\AppData\Roaming\npm-cache\_logs\2018-05-23T05_42_24_691Z-debug.log

**Comment by michaelbromley** [comment]
Hi,

Are you a Windows user? EPERM errors are sometimes caused when trying to npm install while there is still some kind of watch process running. Make sure there are no running node processes which might be watching your node_modules folder when you install.
