### ISSUE TITLE
Issue with multiple paginators in loop

### ISSUE THREAD

**Issue by akshay-borase** [michaelbromley/ngx-pagination#254]
Hi,

Thanks for the awesome component. It is really helpful.
I am facing issue in creating multiple paginators on single page. When I click the next button, it changes the page number for all instances. As per documentation, I am using unique id for each instance but facing same issue.
Please find below code snippet.
Here I am dynamically creating tables based based on "nodeName" received in first ngFor loop and then displaying data in each table (div) in each table in second ngFor loop. It displays the pagination for each table but on click of next button it moves to next page for all tables
![issue](https://user-images.githubusercontent.com/35065967/40414886-1edfc16a-5e97-11e8-8eea-f43259b016af.jpg)

I
```HTML
<div style="display:inline-block;width:50%; padding-top:20px " *ngFor="let data of tabularData">
        <div class="">
          <div class="row dataFormatter">
            <div class="col-12 tabDataPadding dataheader">{{data.nodeName}}</div>
          </div>

          <div class="row table-bordered dataFormatter">
            <div class="col-4 tableBody tabDataPadding">Items</div>
            <div class="col-3 tableBody tabDataPadding">Value</div>
            <div class="col-5 tableBody tabDataPadding">Updated On</div>
          </div>
          <div class="row table-bordered dataFormatter" *ngFor="let tb of data.attributes | paginate: {id: data.nodeName, itemsPerPage:5 , currentPage:p }">
            <div class="col-4 tableBody tabDataPadding">{{tb.key}}</div>
            <div class="col-3 tableBody tabDataPadding">{{tb.value}}</div>
            <div style="font-size:0.9em" class="col-5 tabDataPadding tableBody">{{tb.date}}</div>
          </div>
          <pagination-controls id={{data.nodeName}} (pageChange)="p = $event"></pagination-controls>
    </div>
  </div>
```
=======

**Angular version**: 5.1.1

**ngx-pagination version**: 3.1

**Description of issue**:

**Steps to reproduce**:

**Expected result**:

**Actual result**:

**Comment by michaelbromley** [comment]
Hi,

I'm not sure if this is the reason, but what happens if you bind the id of the pagination-controls using the square bracket syntax?
```HTML
<pagination-controls [id]="data.nodeName" (pageChange)="p = $event"></pagination-controls>
```

**Comment by akshay-borase** [comment]
Hi Michael,
Thanks for the quick reply.
I tried binding as per your suggestion, but it gives same result.

**Comment by michaelbromley** [comment]
Okay, then please try to reproduce the issue in [StackBlitz](https://stackblitz.com/edit/angular-e1f9hq) so I can try to help further.

**Comment by TheBearSO** [comment]
Hello @akshay-borase, 

Have you tried `[attr.id]="data.nodeName"`? Maybe that fix your problems. Check this stackoverflow answer: https://stackoverflow.com/a/34571051/3354228

**Comment by akshay-borase** [comment]
Hello Bruno Sabetta,

I tried [attr.id]="data.nodeName" but it gives below error, but it only shows Next button and don't show page numbes. If click on  Next button it gives below error. You can check it on StalkBlitz link shared above.

The id in paginate pipe and pagination control doesn't map.

ngx-pagination.js:377 PaginationControlsDirective: the specified id "DEFAULT_PAGINATION_ID" does not match any registered PaginationInstance

**Comment by michaelbromley** [comment]
@akshay-borase do you have a link to your Stackblitz reproduction?

**Comment by akshay-borase** [comment]
Ohh ..  forgot to share. Please find below the app link
https://stackblitz.com/edit/angular-95pnxc

**Comment by michaelbromley** [comment]
Thanks for the link. I see the problem now.

You have only a single, shared variable `p` representing the current page. Each instance of pagination is therefore updating this shared variable, which then affects all other instances.

The solution is to use a unique currentPage variable for each instance. One way to do it is like this:

```TypeScript
p: { [id: string]: number} = {};
```

```HTML
<div *ngFor="let tb of data.attributes | paginate: {id: data.nodeName, itemsPerPage:3 , currentPage: p[data.nodeName] }">

<pagination-controls [id]='data.nodeName' (pageChange)="p[data.nodeName] = $event"></pagination-controls>
```

See [this updated demo](https://stackblitz.com/edit/angular-bjrvoz).
