### ISSUE TITLE
Pagination in mobile devices

### ISSUE THREAD

**Issue by Liahus3003** [michaelbromley/ngx-pagination#256]
I have been using this pagination and I like it very much , but one thing I would like to be interested in is the pagination setting specifically for mobile , like specified in the description of https://foundation.zurb.com/sites/docs/pagination.html
![page](https://user-images.githubusercontent.com/39612581/40527832-e83c3ece-600b-11e8-9a6b-91d13c5c6162.PNG)

**Comment by michaelbromley** [comment]
Hi,

I'll consider this for a future release. For now it can be achieved via [custom pagination templates](https://github.com/michaelbromley/ngx-pagination#paginationcontrolsdirective)
