### ISSUE TITLE
How to handle dynamic server side paginate config using ngFor ?

### ISSUE THREAD

**Issue by frontend123** [michaelbromley/ngx-pagination#257]
This is component is very useful for my use case. I have one issue in handling different paginate config. I will get inputs like records per page, total rows and current page from server along withe the data. 

My data looks like this:

Records per page and page numbers will be unique for each object.

```json
[{
		"chartId": "chart_vh_name",
		"type": "bar",
		"totoalRecords": 83,
		"rowsPerPage": 30,
		"pageNumber": 3,
		"data": {
			"barline": [{
					"values": [{
							"value": 5340967,
							"label": "test"
						}, {
							"value": 4510751,
							"label": "test 123"
						}, {
							"value": 2603405,
							"label": "test 456"
						}
					]
				}
			]
		}
	}, {
		"chartId": "chart_year",
		"type": "bar",
		"totoalRecords": 42,
		"rowsPerPage": 10,
		"pageNumber": 1,
		"data": {
			"barline": [{
					"values": [{
							"value": 3133511,
							"label": "2007"
						}, {
							"value": 3013510,
							"label": "2015"
						}, {
							"value": 2711138,
							"label": "2016"
						}
					]
				}
			]
		}
	}
]
```

=======

**Angular version**: 4.3

**ngx-pagination version**: 3.1.1

**Description of issue**:

**Steps to reproduce**:

**Expected result**:

**Actual result**:

**Demo**: (if possible, edit [this StackBlitz demo](https://stackblitz.com/edit/angular-e1f9hq) and paste the link to your fork)

Any relevant code:
```HTML
<div class="col-md-6" *ngFor="let VehicleCharts of VehicleChartResponse | paginate: { itemsPerPage: VehicleCharts.rowsPerPage, id: VehicleCharts.chartId, totalItems: VehicleCharts.pageCount, currentPage: VehicleCharts.pageNumber}; index as i">
        <app-bar-chart style="width: 100%" *ngIf="VehicleCharts.type == 'bar'" [chartId]="VehicleCharts.chartId" [chartKey]="VehicleCharts.chartKey" [xAxis]="VehicleCharts.xAxis" [yAxis]="VehicleCharts.yAxis" [data]="VehicleCharts.data.barline"></app-bar-chart>
        <pagination-controls (pageChange)="pageChanged($event, VehicleCharts.chartId, i)" [id]="VehicleCharts.chartId"></pagination-controls>
</div>
```
--- In this scenario i am not able to assign values dynamically.

**Comment by michaelbromley** [comment]
Hi,

It's not totally clear to me what you are trying to achieve here. Do you want to have multiple instances of the pagination on page? 

If you can put together a reproduction of the issue based on the linked StackBlitz demo above, this would help immensely.

**Comment by frontend123** [comment]
Hi,

Thanks for responding quickly. I added my code in this link [https://angular-e1f9hq.stackblitz.io](Link) but for reason it is not saving. I am putting my code here in the comment. I am able to achieve the whole functionality but my contents are duplicated. refer to the screenshot below.
`<div class="text-center">
	<h1>ngx-pagination live demo</h1>
	<h4><small><a href="https://github.com/michaelbromley/ngx-pagination">GitHub Repo</a></small></h4>
	<p>A bare-bones demo for your experimenting / bug-reproducing pleasure.</p>
</div>

<div *ngFor="let VehicleCharts of VehicleChartResponse; let k = index;" >
<div class="col-md-6" *ngFor="let VehicleCharts of VehicleChartResponse | paginate: { itemsPerPage: VehicleCharts.rowsPerPage, id: VehicleCharts.chartId, totalItems: VehicleCharts.totoalRecords, currentPage: VehicleCharts.pageNumber}; index as i">
<div>
  {{VehicleCharts.chartId}}
</div>
        <pagination-controls (pageChange)="pageChanged($event, VehicleCharts.chartId, i)" [id]="VehicleCharts.chartId"></pagination-controls>
</div>
</div>`

App Component:

`import { Component } from '@angular/core';

@Component({
  selector: 'my-app',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  VehicleChartResponse;
  collection = [];
    public pageChanged(event: any, chartId, index): void {
// here i am firing service request
  }
  constructor() {
    this.VehicleChartResponse = [{
		"chartId": "chart_vh_name",
		"type": "bar",
		"totoalRecords": 83,
		"rowsPerPage": 30,
		"pageNumber": 3,
		"data": {
			"barline": [{
					"values": [{
							"value": 5340967,
							"label": "test"
						}, {
							"value": 4510751,
							"label": "test 123"
						}, {
							"value": 2603405,
							"label": "test 456"
						}
					]
				}
			]
		}
	}, {
		"chartId": "chart_year",
		"type": "bar",
		"totoalRecords": 42,
		"rowsPerPage": 10,
		"pageNumber": 1,
		"data": {
			"barline": [{
					"values": [{
							"value": 3133511,
							"label": "2007"
						}, {
							"value": 3013510,
							"label": "2015"
						}, {
							"value": 2711138,
							"label": "2016"
						}
					]
				}
			]
		}
	}
]
  }
}
`

Screen shot:

![pagination](https://user-images.githubusercontent.com/9474837/41242406-0878cfde-6d65-11e8-9176-23eb43236959.PNG)

**Comment by michaelbromley** [comment]
Hi,

First, a couple of tips to help you in future issues: 

1. For code blocks, you should surround the code with three backticks followed by the language, e.g. 

` ```TypeScript `
(your code here)
` ``` `

2. The reason you couldn't save your changes to the StackBLitz demo may well be because you need to fork it first.

Anyway, back to your issue:

From the code you show, there seems no way that the items would be duplicated as in the screenshot. You have a hard-coded array with 2 items, so looping over them with `ngFor` could only ever yield 2 instances, not 4.

This makes me suspect that the culprit might be in the `pageChange()` method which you didn't show. Perhaps you are mutating the array in some way which leads to the duplication?

Please show me that method in full so I can get a better idea.

**Comment by frontend123** [comment]
Hi ,
Here I have updated  my code in [https://angular-ynkgpk.stackblitz.io](url).

**Comment by michaelbromley** [comment]
Thanks. I see the issue causing the duplication - you have 2 nested `ngFor` loops looping over the exact same array (`VehicleChartResponse`).

Perhaps you intend to do something more like [this](https://stackblitz.com/edit/angular-wcxwt8)?

**Comment by frontend123** [comment]
Hi thanks for the update. looks like for this particular use case i am not able to use pagination. i have used ngx pagination for a different use case which worked very well.

**Comment by Thirumadhu** [comment]
How to create pagination for this 1, 3, 7, 9, 12, 16, 17, 18, 19, 20, 22, 24, 25, 26, 27, 28, 31, 34, 36. If I click the next the page number should be 3 then if I click again next the page number should be 7, Using these random values we need to create pagination in angular. 
The pagination index should come to an above-mentioned number. This will come every time a random number we have a populate page number random numbers.
