### ISSUE TITLE
Ellipsis class is not being added to 'three dots'

### ISSUE THREAD

**Issue by Marina-R** [michaelbromley/ngx-pagination#263]
Hi Michael!

First of all, thank you for the great work you've done. One thing I've noticed, that .ellipsis class is not being added to the rendered pagination, so it a bit complicated to style this block differently, or manipulate it in any other way.

Would be great if this could be fixed in other versions. 

Thanks in advance.

**Comment by michaelbromley** [comment]
Hi Marina,

That's a good suggestion. I'll add it as a feature for the next version, which I suppose I should work on soon 😅
