### ISSUE TITLE
how can i change my position of prvious and next in ngxpagination

### ISSUE THREAD

**Issue by lakshmitejaswi** [michaelbromley/ngx-pagination#267]
hi 
how can i change position of previous and next in pagination control

**Comment by michaelbromley** [comment]
You can [use CSS](https://github.com/michaelbromley/ngx-pagination/tree/737cc1611ae3ceb7150e6aad5efed67b10ba0a54#styling), or if that is not sufficient for you needs, write a [custom pagination controls component](https://github.com/michaelbromley/ngx-pagination/tree/737cc1611ae3ceb7150e6aad5efed67b10ba0a54#paginationcontrolsdirective) and structure and style it however you like.
