### ISSUE TITLE
SyntaxError: Unexpected token import in SSR

### ISSUE THREAD

**Issue by MortezaAghili** [michaelbromley/ngx-pagination#270]
**Angular version**: ^4.0.0

**ngx-pagination version**: ^3.2.0

**Description of issue**: 
I'm using Angular Universal for SSR mode and I need to use ngx-pagination for my list of products. But when I run it I'll get an error like below.

**Actual result**:
```
/dist/ngfactory/node_modules/ngx-pagination/dist/ngx-pagination.ngfactory.ts:9
import * as i0 from '@angular/core';
^^^^^^
SyntaxError: Unexpected token import

```

**Comment by michaelbromley** [comment]
Hi,

I've got no experience with SSR, so I'm not sure what's up off the top of my head. Are you able to put together a minimum reproduction of the issue as a git repo I could run?
