### ISSUE TITLE
providing ID in pagination-controls hiding the pagination component

### ISSUE THREAD

**Issue by reddevilzee** [michaelbromley/ngx-pagination#278]
**Angular version**: 6.1

**ngx-pagination version**: 3.2.1

**Description of issue**: 
I see ID as one of the element in pagination controls. But using it is hiding the pagination component. I have provided the stackblitz with the example.

**Demo**: with ID : https://stackblitz.com/edit/angular-ojtln3?file=app/app.component.html
   without ID : https://stackblitz.com/edit/angular-e1f9hq (provided demo)

**Comment by michaelbromley** [comment]
Hello,

Here is the relevant part from the docs:

> id [string] If you need to support more than one instance of pagination at a time, set the id and ensure it matches the id set in the PaginatePipe config.

In other words, you need to also set the same id string as a property of the config object passed to the `paginate` pipe:

```html
<li *ngFor="let item of collection | paginate : { currentPage: p, itemsPerPage: 10, id: 'pagination' }">...</li>
```

**Comment by reddevilzee** [comment]
@michaelbromley thank you for clarifying. appreciate it.
