### ISSUE TITLE
How can I stay in current page after refresh website ?

### ISSUE THREAD

**Issue by Omar-Qalei** [michaelbromley/ngx-pagination#279]
**HTML5**
```
<div class="list">
      <pagination-controls (pageChange)="p = $event"></pagination-controls>
 </div>
```

**TS**

`p = 1`

**Comment by egemenu** [comment]
I think you better to use query-parameters.

Duplicate of #229

**Comment by Omar-Qalei** [comment]
Can you give me example please ?
If I use database will effect to other users

**Comment by egemenu** [comment]
What does it have to be with database? I can't follow.
