### ISSUE TITLE
Return to 1st page after new response returned by server

### ISSUE THREAD

**Issue by bromoapp** [michaelbromley/ngx-pagination#280]
=======

**Angular version**: 6

**ngx-pagination version**: 3.2.0

**Description of issue**: 
I have a search result page, and your awesome pagination at its bottom, at the top of this page is a search input. My problem is: after user navigate to other page (after the 1st page), let say 6th page... then the user input another search arguments at search input then submit... the page doesn't return to the 1st page after new list of results rendered. I already emptied the array that caused the paging but still doesn't changed.

**Steps to reproduce**:

**Expected result**:
Expected result is: after user navigate to other page than 1st... when ever the array that generates the paging at in the first place is emptied ... the paging will reset to the 1st page.

**Actual result**:

**Demo**: (http://hargadil.com/search?q=iphone%20x

Any relevant code:
```

```

**Comment by michaelbromley** [comment]
Hello. You can do this by setting the value of `currentPage` to 1 manually whenever the search term is changed.

**Comment by bromoapp** [comment]
Great :) ... Thanks

**Comment by bromoapp** [comment]
Hi, I did injecting PaginationService into constructor of the component that trigger search request to server like below:

    constructor(private apiService: RestApiService, private pagingService: PaginationService) { }

    ngOnInit() {}

    ngOnChanges() {
        this.pagingService.setCurrentPage("", 1); // sets page to 1
        this.products = [];                                   // reset array that populate paging
        this.doSearch(this.arguments);                // initiate search request to API
    }
`
My question is: how to set the ID of my paging instance?
Note: I really really use the basic setup of your component
Thanks

**Comment by michaelbromley** [comment]
Generally you shouldn't need to inject the `PaginationService`. This is intended for internal use within the library, which is why it is not even documented. 

It should be sufficient to bind to a variable on the component (`p` in [the simple example](https://github.com/michaelbromley/ngx-pagination#simple-example)) and in your `ngOnChanges` method above, do:

```ts
ngOnChanges() {
    this.p = 1;
    this.products = [];                                   // reset array that populate paging
    this.doSearch(this.arguments);                // initiate search request to API
}
```
