### ISSUE TITLE
How to use pagination pipe directly in service?

### ISSUE THREAD

**Issue by uberspeck** [michaelbromley/ngx-pagination#283]
**Angular version**: 7.1.0
**ngx-pagination version**: 3.2.1

**Description of issue**:
My app depends on [ngxs-store](https://ngxs.gitbook.io/ngxs/) for state management. The state store has [memoized selectors](https://ngxs.gitbook.io/ngxs/concepts/select#memoized-selectors) to allow selection of subsets of state data. I would like to handle the pagination _inside_ the selector so all data mutation is handled at once. I've tried using the `PaginationPipe` directly, but I can't seem to get it working. 

```typescript
// ...import all the things, etc

export const initialState = {
  pages: [],
  focusedPage: null,
  selectedPages: [],
  searchText: null,
  sortKey: 'pgIndex',
  searchColumns: ['pgNumber', 'text'],
  filters: [],
  paginationId: 'pageList',
  itemsPerPage: 15,
  currentPage: 1,
};

@State<BookPagesStateModel>({
  name: 'pages',
  defaults: initialState
})
export class BookPagesState {

  @Selector()
  static filteredPages(state: BookPagesStateModel) {

    let pages = state.pages;

    // Handle sort
    if (state.sortKey) {
      pages = new SortByPipe()
          .transform(pages, state.sortKey);
    }

    // Handle search
    if (state.searchText) {
      pages = new SearchForPipe()
          .transform(pages, state.searchText, state.searchColumns);
    }

    // Handle filters
    if (state.filters.length) {
      pages = new ApplyFiltersPipe()
          .transform(pages, state.filters);
    }

    // Handle pagination - NOT WORKING :(
    // ******************************************
    pages = new PaginatePipe(new PaginationService())
        .transform(pages, {
          id: state.paginationId,
          itemsPerPage: state.itemsPerPage,
          currentPage: state.currentPage
        });

    return pages;
  }

}
```

BTW, thx for creating an awesome lib!

**Comment by michaelbromley** [comment]
Hi,

Interesting use case. I've never considered using it directly before, so this is new territory! But in theory it should be possible.

> but I can't seem to get it working

Can you expand on this? What do you expect and what happens currently?

Off the top of my head it may be a problem of injector scope, i.e. the `<pagination-controls>` component / directive implicitly injects an instance of the `PaginationService`, but since you are directly constructing it in your code, then it won't get the same instance as the one the pipe is using.

So a solution might be to inject the `PaginationService` into your `BookPagesState` class and pass *that* into the pipe constructor. This should then provide the same instance of the `PaginationService` as is being used by the pagination controls component.

**Comment by uberspeck** [comment]
Thanks for the quick reply! I think you're right (re: different instances). This is what my pagination looks like for a 600+ page book...

![screen shot 2018-11-28 at 7 39 07 am](https://user-images.githubusercontent.com/857256/49159121-fca3f600-f2e0-11e8-8f3c-f8634ba814d4.png)

Just a _little_ off ;) It gets the items per page correct (15 in this case), but I can't move to the next set etc. I think one problem is the state selectors have to be static so I can't figure out how to inject the service. Everything I'm finding online suggests I'm "doing it wrong" (services in static methods === 'bad') but I can't seem to figure out what's "right".  I've even [tried workarounds](https://stackoverflow.com/questions/49507928/how-to-inject-httpclient-in-static-method-or-custom-class) to no avail

**Comment by michaelbromley** [comment]
Ah okay, I didn't notice that the selector was a static method. I have no idea about ngxs, but here are a couple of ideas:

* inject the `PaginationService` into the component/service which calls `filteredPages` and pass the instance in as an argument. If for some reason the call must only take a single "state" argument, you could use a higher-order function to achieve the same.
* if it gets too complex, I think you might have to concede that you are trying to bend this lib into a form for which it is not intended! Either implement the paging yourself or just use the lib as described in the docs.

For what it's worth, when I use this lib with a single state store, I just store the itemsPerPage and currentPage in the state and let the pipe do the rest when it needs to. If you generally use the onPush change detection strategy, this is pretty efficient (if perf is your main concern).

**Comment by uberspeck** [comment]
Thanks @michaelbromley! You may be right that I have to just implement this myself. In most places on the site your lib works perfectly. However, in this case, a user may highlight individual items in the list and navigate between them etc. Obviously applying the pagination after the fact causes issues with tracking the selected item the next/previous item in the list etc. Anyway, i'll keep banging on it, thanks for a great lib!
