### ISSUE TITLE
hide the Previous and Next label when only one page is available

### ISSUE THREAD

**Issue by mSafdarAli** [michaelbromley/ngx-pagination#287]
**Angular version**: 6

**ngx-pagination version**: 3.2.1

**Description of issue**: can't figure it out how to hide previous and next label

**Steps to reproduce**:

**Expected result**:

**Actual result**:

**Demo**: (if possible, edit [this StackBlitz demo](https://stackblitz.com/edit/angular-e1f9hq) and paste the link to your fork)

Any relevant code:
```

```

**Comment by michaelbromley** [comment]
Hi,

Please state what you have tried so far. Right now there is nothing for me to go off.

**Comment by mSafdarAli** [comment]
<pagination-template *ngIf="total_records > 0" id="data" #p="paginationApi" (pageChange)="changePage($event)">
    <div class="categories-after-pagination">
      <nav class="categories-pagination">
        <ul>
          <li *ngIf="p.isLastPage()"><a id="prev" class="page-numbers" (click)="p.previous()">Prev</a></li>
          <li *ngFor="let page of p.pages"><a class="page-numbers" [class.current]="p.getCurrent() === page.value" (click)="p.setCurrent(page.value)">{{ page.label }}</a></li>
          <li *ngIf="p.isFirstPage()"><a id="next" class="page-numbers next" (click)="p.next()">Next</a></li>
        </ul>
      </nav>
      <p class="categories-result-count">Showing {{ record_start }}–{{ record_end }} of {{ total_records }} results</p>
    </div>
  </pagination-template>

this is the pagination template I am using. It's working awesome. Problem is, when there is only one page to show, it's still showing pre and next labels. I have tried many things like angular ngif template but no use.
can you please guide me through this? 
Thank you.

**Comment by mSafdarAli** [comment]
found a way.
i use a condition total_records > 0 then show pagination 
that's all. closing this issue. Thank you.

**Comment by michaelbromley** [comment]
Glad you got it figured out 👍
