### ISSUE TITLE
Wrong last page

### ISSUE THREAD

**Issue by lnrdolopez** [michaelbromley/ngx-pagination#289]
Hi, Michael, im looking around about someone with same problem, im getting an empty last page (100) when the real last one is 99, i still dont know wait it happens.

Im in angular 6, i have this { itemsPerPage: 10, currentPage: p, totalItems: res.total } with res.total = 993 and p=1

**Comment by michaelbromley** [comment]
Hi, are you able to create a demo that reproduces this behaviour so I can look into it? Edit [this StackBlitz demo](https://stackblitz.com/edit/angular-e1f9hq) and paste the link to your fork

**Comment by lnrdolopez** [comment]
Hi, my problem is with the paged server side response, it returns the first page with data from the second. The real problem is that, the first page is missed, so a backend error, but the total is right so the front pagination is ok.

Sorry is not an issue, thanks for your response
