### ISSUE TITLE
Page No link and Previous button is not working on mat-dialog

### ISSUE THREAD

**Issue by srahulk1** [michaelbromley/ngx-pagination#290]
**Angular version**: 5

**ngx-pagination version**: 2
 
**Description of issue**: I have been using it on normal components its working fine but when I am trying to access it on a screen which is being opened as popup screen next button is working fine but page number link and previous link is not working,

**Steps to reproduce**: 
1.Create any component with an array of few objects
2. Display the component as popup screen using mat-dialog component
3. Use *ngFor to display object using paginate pipe
4.  Try clicking on next button - It will work
5. Try clicking previous and any other page number option it won't work.

**Expected result**:

1. Data should change on click of the page number.
2.  The previous button should work too

![image](https://user-images.githubusercontent.com/38346966/50681087-21059780-1030-11e9-8199-081dfa3e3611.png)

**Actual result**:

Any relevant code:
```
<div class="row" *ngFor="let flight of flightSearchResult|paginate: { itemsPerPage: 4, currentPage: p }">

</>

<pagination-controls class="d-flex justify-content-end" (pageChange)="p = $event"></pagination-controls>
```

**Comment by michaelbromley** [comment]
Hi,

Please provide a minimal reproduction of this issue otherwise it is impossible for me to advise. Edit [this StackBlitz demo](https://stackblitz.com/edit/angular-e1f9hq) and paste the link to your fork
