### ISSUE TITLE
Regarding jump to page and items per page options

### ISSUE THREAD

**Issue by abhi747** [michaelbromley/ngx-pagination#291]
Hi Michael! 

I need to know if following options are available or not with ngx-pagination and if available, how to use them.

- Jump to particular page option, where user can enter a page number he wants to navigate to into a text box which is generally present along side the pagination controls and after submitting the page number, the particular page is opened in the table.

- Set items per page option for user, where user can set items per page in a drop-down menu generally present along side pagination controls. The dropdown can contain configurable values like 10, 20, 50, etc records to be shown per page.

This two features will be highly useful if available.

**Comment by michaelbromley** [comment]
Hi,

Yes, both of these can be done with this lib:

1. The default controls component does not include a page number input. You'd have to make a custom template yourself for this. See the docs here: https://github.com/michaelbromley/ngx-pagination#paginationcontrolsdirective

2. For this you'd just need to put a select input somewhere and bind its value to the same variable used as the `itemsPerPage` argument which is passed to the `paginate` pipe.
