### ISSUE TITLE
Custom server side pagination

### ISSUE THREAD

**Issue by abhi747** [michaelbromley/ngx-pagination#293]
Hi

This is not an issue but just want to know if the required functionality is possible.
Currently the server side pagination option with ngx paination is such that we can fetch data for every page separately from back end with pageChange() event handler available.

But we need a configurable pagination as follow - 
Initially specific number of records will be fetched from the back end, say 50 records and along with that we will also get count of total records available at back end, say 200 records.

That total count can be set to totalItems parameter in paginate pipe to configure page controls.

We need to display specific number of records per page say, 10 records. So upto the 50 records fetched already or first 5 pages (totalRecords(50)/recordsPerPage(10)), we need to have client side pagination. But once user navigates page beyond the count of already fetched records, that is record beyond 50th record or beyond 5th page say 6th or further page, we need to fetch further records from back end, thus having server side pagination.

Thus it is mixture of client side and server side pagination. I research for it with lot of arithmetic calculations to handle pagination but something breaks every time.

Would be glad if you can guide with a solution for such functionality if possible.

Thanks.

**Comment by michaelbromley** [comment]
Hi,

I've never had to implement anything like that before, but I think there *should* be some way to do it. I'd be thinking along the lines of a service which "proxies" the actual server calls and exposes what looks to be a single page of data at a time. Of course, this would then involve a bit of duplication of paging logic, but should be possible.

You can always try it out in a simple StackBlitz demo and if you have trouble I can take a a look and see if I can help.
