### ISSUE TITLE
Server side pagination with custom filter

### ISSUE THREAD

**Issue by abhi747** [michaelbromley/ngx-pagination#294]
Hi

I have added a custom pipe for filtering the list according to the text entered in the search box and it is working properly with client side ngx pagination. But I need to use this with server side pagination.

But in server side pagination the number of 'page links' are displayed according to the 'totalItems' count. So, I suppose after filtering the list with custom pipe, if the matching records in the list are less than initial records in the list, how the number of 'page links' could be adjusted according to that? For example, lets say initially there are fifty records in the list and number of page links are 5 according to 10 records per page. After filtering through the custom pipe, the number of records become 7, then only one page link should be displayed. Any idea how to achieve that?

Thanks.

**Comment by michaelbromley** [comment]
Hi,

If you are doing server-side paging, it also implies that your filtering should be done on the server side too. Otherwise it is not possible to know the true number of results from the filter operation.

**Comment by abhi747** [comment]
Hi 

Thanks for the quick response. I agree that for server side pagination, filtering should be also server side. Still, if you don't mind I want to know whether by some way it is possible to achieve by the pipe I have created as follow - 

```
//pipe
@Pipe({ name: 'filterList' })
export class FilterPipe implements PipeTransform {
  transform(array, searchText) {
    if(!searchText)
      return array;

     return array.filter(item => item.indexOf(searchText) >- 1);
  }
}

//template
<li *ngFor="let item of collection | filterList: search | 
      paginate: config">{{ item }}</li>
```
What I am thinking, is that passing the component field assigned to totalRecords parameter in the paginate pipe to above custom filter pipe and calculate the length of filtered array in the custom filter pipe. After that just need to assign that length to the component field assigned to totalRecords parameter in the paginate pipe.

But I am unaware whether a component field can be modified from custom pipe in angular.

**Comment by michaelbromley** [comment]
I'm sorry, I don't fully understand what you are trying to do here.

If you are doing server side pagination, then at any given time you have at most 1 page of results in memory (say, 10). If you then filter those 10 results, then by definition you can never have more than 10 results afterwards, so the idea of paginating becomes moot.

If the pagination is supposed to represent "other pages of results matching the filter", then how can you possibly know this without loading all results from the server and doing the entire pagination in memory?

Perhaps I am missing something here. Try to explain it to me a bit more simply.

**Comment by abhi747** [comment]
Hi
Sorry for not providing the context and this late reply.

Actually we needed custom server-side pagination exactly as described by me at https://github.com/michaelbromley/ngx-pagination/issues/293

I have achieved that functionality with some arithmetic calculations.

So, in this case we have more than one page in memory at client side even though it is server side pagination (as we are dividing the records fetched from server into few chunks of pages).

So, we need to have a filter functionality to filter these records across multiple pages based on text enetered by user in the search box. The filtering functionality I think will filter the records properly but only the totalRecords in the paginate pipe needs to get updated according to the length of filtered records array. for updating the number of page links in the pagination.

I am think of using Eventemitter to emit the length of filtered records array in the pipe shown above before returning the filtered records array and subscribing it in the component where the totalRecords need to be updated. Will try out this soon.

Please let me know if you can suggest any better approach.

**Comment by michaelbromley** [comment]
Ah okay, I understand a bit better now :)

Okay, another way of doing it could be to put your filter in the component, where it is easy to access and update the new total items count. The downside is that it could be less performant than a pipe. But if you are using the OnPush change detection strategy it might be comparable.

**Comment by abhi747** [comment]
> Okay, another way of doing it could be to put your filter in the component, where it is easy to access and update the new total items count

Okay. But by putting filter into the component instead in pipe will directly modify iterating array in the component, whereas using pipe we can filter the array only in the view without modifying the actual array, right?

Because we need the iterating array immutable as far as possible, because there are other operations like sorting which will have impact on it.

**Comment by michaelbromley** [comment]
I think you could return a new array from the filter function which will not mutate the original one:

```ts
class MyComponent {
   filteredResults(term: string) {
     const result = this.items.filter(myFilterFunction);
     this.totalItems = result.length;
     return result;
  }
}
```

```html
<li *ngRepeat="filteredResults() | paginate: { currentPage: p, totalItems: totalItems }">....</li>
```

**Comment by abhi747** [comment]
Thanks. This is a good way as well.

But I think building something reusable for such functionality like a pipe which can be used across components would be more useful. Again, I understand both ways has its tradeoffs like you said, in case of reusable pipe - difficulty in getting data back in component ('total items' count )and in case of adding filtering logic in directly inside component - hampering its reusability.
