### ISSUE TITLE
Page number is not retained when navigating to a secondary outlet

### ISSUE THREAD

**Issue by sachin276773** [michaelbromley/ngx-pagination#295]
=======

**Angular version**: 6.0

**ngx-pagination version**: 3.2.1

**Description of issue**: 

I have implemented a custom pagination component using PaginationControlsDirective.

I have a requirement where in I have to open a dialog component (pop up) as a secondary outlet from the pagination component. Scenario is:

Have a parent component.

Pagination component is the primary outlet.

Dialog/popup is the secondary outlet.

Now on a button click, I call router.navigate to secondary outlet:

ISSUE: When the pop up comes up, the page number is not retained and the page goes back to first 

**page.**

**Steps to reproduce**:

**Expected result**:

**Actual result**:

**Demo**: (if possible, edit [this StackBlitz demo](https://stackblitz.com/edit/angular-e1f9hq) and paste the link to your fork)

Any relevant code:
```

```

**Comment by michaelbromley** [comment]
In this case, you are responsible for retaining the state. The way I normally do it is to put the current page in the URL as a param.

**Comment by artworkjpm** [comment]
I have the same problem, when the user clicks to another page then goes back, the pagination defaults to page 1. @michaelbromley could you give me some pointers to put createPage as a para in the url? if you think this is the best solution?

**Comment by michaelbromley** [comment]
@artworkjpm take a look at this code: https://github.com/vendure-ecommerce/vendure/blob/master/admin-ui/src/app/common/base-list.component.ts

It shows how I use ngx-pagination in my own apps - I treat the URL as the source of truth, so the `(pageChange)` event does nothing more than setting a url parameter. The `currentPage` value is derived from the params into an observable:
```
        this.currentPage$ = this.route.queryParamMap.pipe(
            map(qpm => qpm.get('page')),
            map(page => (!page ? 1 : +page)),
```

**Comment by artworkjpm** [comment]
Do I use all the code of base-list.component.ts or just parts of it? I have tried using parts of it, relevant to currentPage, with no success, I find it difficult to understand your solution as I am quite new to Angular.

**Comment by michaelbromley** [comment]
> as I am quite new to Angular

I see. I suggest then that you try a different place to get help. Not that I don't want to, but I have limited time and since this is not an issue specifically to do with this lib, it is better suited to a forum like StackOverflow. Good luck getting it solved!
