### ISSUE TITLE
The pipe 'paginate' could not be found 

### ISSUE THREAD

**Issue by Jawadh-Salih** [michaelbromley/ngx-pagination#297]
Hi, 
I have included a pagination enabled component in to lazy loaded module. But it throws me the titled error. I have included the NgxPaginationModule as well. 

Could you please tell me what is I am missing here? 

Thank You. 

=======

**Angular version**: 6.1.0

**ngx-pagination version**: 3.2.1

**Comment by michaelbromley** [comment]
Hi,

You'll have to provide some more details about your setup. Is the `NgxPaginationModule` imported into the lazy-loaded module where the component in question is declared?

**Comment by Jawadh-Salih** [comment]
Hi, It is fixed. Thank you for the comment. :). I have to export the created custom PaginationationComponent.
