### ISSUE TITLE
First page of Pagination is a blank page

### ISSUE THREAD

**Issue by matheusribeirogarcia** [michaelbromley/ngx-pagination#301]
Angular: 7.2.12

ngx-pagination version: 3.2.1

Description of issue: 

On first load: localhost:4200
First page of Pagination is a blank page:
https://imgur.com/kwWsLiD

So I need to click the button 'Next' to go to the actual first page:
https://imgur.com/zJTpW7Y
Setting the property currentPage to any value doesn't seen to make any difference.

If I click another button, that shows another content:
https://imgur.com/X0nGsNA

Then I click to the button that shows the data with pagination the page number 1 is blank:
https://imgur.com/CALAuaM

So I need to go to the second page and go back to the first page to see page number 1 content:
https://imgur.com/FMDsYOa
https://imgur.com/ZPy3KDc

I can see in console that error:
`PaginationControlsDirective: the specified id "DEFAULT_PAGINATION_ID" does not match any registered PaginationInstance : ngx-pagination.js:395 `

**Expected result**:
On load: First page should have the documents loaded, not a button to click.

Code is almost the same as your examples on basic pagination:

A component that shows data
```
<div class="container py-4">
  <mat-card>
    <mat-card-title>Sites:</mat-card-title>
    <mat-card-content>
      <div *ngFor="let siteSource of siteSources  | paginate: { itemsPerPage: 5, currentPage: page, DEFAULT_PAGINATION_ID: 1}">
        <site-details [site]='siteSource._source'></site-details>
      </div>
    </mat-card-content>
    <mat-card-actions>
      <pagination-controls responsive="responsive" [previousLabel]="labels.previousLabel" [nextLabel]="labels.nextLabel"
        [screenReaderPaginationLabel]="labels.screenReaderPaginationLabel"
        [screenReaderPageLabel]="labels.screenReaderPageLabel"
        [screenReaderCurrentLabel]="labels.screenReaderCurrentLabel" (pageChange)="page = $event">
      </pagination-controls>
    </mat-card-actions>

  </mat-card>
  <router-outlet></router-outlet>
</div>
```
and its Ts file:

```
import { Component, OnInit, ChangeDetectionStrategy, Input } from '@angular/core';

import { ElasticsearchService } from '../../elasticsearch/elasticsearch.service';
import { SiteSource } from '../site.interface';

@Component({
  selector: 'show-sites',
  templateUrl: './show-sites.component.html',
  styleUrls: ['./show-sites.component.css'],
  changeDetection: ChangeDetectionStrategy.OnPush
})

export class ShowSitesComponent implements OnInit {

  private static readonly INDEX = 'contentman';
  private static readonly TYPE = 'sites';

  siteSources: SiteSource[];
  page: number = 1;

  public labels: any = {
    previousLabel: 'Página anterior',
    nextLabel: 'Próxima página',
    screenReaderPaginationLabel: 'Pagination',
    screenReaderPageLabel: 'page',
    screenReaderCurrentLabel: `You're on page`,
};

  constructor(private es: ElasticsearchService) {}
  
  ngOnInit() {
    this.es.getAllDocuments(ShowSitesComponent.INDEX, ShowSitesComponent.TYPE).then(
      response => {
        this.siteSources = response.hits.hits;
        console.log(response);
      }, error => {
        console.error(error);
      }).then(() => {
        console.log('Show Site Completed!');
      });
  }
}
```

**Comment by matheusribeirogarcia** [comment]
I can see that page saves the page I were before changing to another content, is there a way to reload all variables when I comeback to that page? Maybe this would fix the second bug

**Comment by michaelbromley** [comment]
Hi,

It might possibly be a change detection issue. What happens if you inject the `ChangeDetectorRef` and the in the subscriber of `getAllDocuments`, after `this.siteSources = response.hits.hits;` add the line `this.changeDetectorRef.markForCheck();`?

**Comment by matheusribeirogarcia** [comment]
Hi, 
Thanks for your awnser! As you thought, it was indeed a `ChangeDetectorRef `problem, setting my `changeDetection: ChangeDetectionStrategy.OnPush `to `changeDetection: ChangeDetectionStrategy.Default` fixed all issues I was having :)
