### ISSUE TITLE
Losing Type on applying pagination pipe

### ISSUE THREAD

**Issue by johnfrades** [michaelbromley/ngx-pagination#303]
=======

**Angular version**:
7.1.4

**ngx-pagination version**:
3.2.1

**Description of issue**:
I lose type when i put "| paginate" on ngFor, because the PaginationPipe is on any type.
I just wanna ask is there any other way to implement the pagination? its not really a problem at all but it kinda sucks that we gonna lose the type on the HTML

Thank you!

**Comment by michaelbromley** [comment]
Hi,

I guess the solution should just be to update the signature of the [`PaginatePipe.transform()` method](https://github.com/michaelbromley/ngx-pagination/blob/ec1249e42536e0f669b6762efef9fec776f038f8/src/paginate.pipe.ts#L27) to be generic, i.e.

```TypeScript
public transform<T = any>(collection: T[] | ReadonlyArray<T>, args: any): T {
 // ..
}
```
You could try manually editing the d.ts file in your node_modules to the above and see if that then fixes it for you. If so I could include the change in a new version. Alternatively if you'd like to have a go at submitting a pull request, please feel free.

**Comment by johnfrades** [comment]
Hey man, i tried it and it work, but this code

`transform<T = any>(collection: T[], args: any): T[];`

**Comment by michaelbromley** [comment]
Did the `ReadonlyArray<T>` part cause an issue? It is there because some people use read only arrays in their components, and without it as part of the `collection` arg type, this can lead to ts errors.

**Comment by johnfrades** [comment]
Yes man, sorry i put it back and everything works fine. 
Thanks! i've sent a pull request
