### ISSUE TITLE
Metadata Mismatch With New Version?

### ISSUE THREAD

**Issue by mstruppBE** [michaelbromley/ngx-pagination#305]
With the latest version of ngx-pagination installed, we're getting the following error when we attempt to build our project using Angular CLI:

> ERROR in Metadata version mismatch for module C:/Users/<Name>/Source/Repos/<Project>/node_modules/ngx-pagination/dist/ngx-pagination.d.ts, found version 4, expected 3, 

We are using Angular version 4.0.2, and attempting to use ngx-version 3.3.0

Any clue on how to fix this? Thanks!

**Comment by michaelbromley** [comment]
Hi,

Oh, I guess this has to do with the fact that I built the new version with Angular 8. I did try to find out if there was any incompatibility with the metadata but did not find anything, and assumed it would be ok.

I suggest you revert to 3.2.1 for now until I have time to investigate further.

**Comment by michaelbromley** [comment]
Ah it looks like between Angular v4 (which was used to build v3.2.1 of this lib) and v5 they changed the metadata format.

I should have made this a major release since it is now a breaking change. I will do this tomorrow.

**Comment by michaelbromley** [comment]
Please try updating to v3.3.1 and see if that resolves the issue for you.
