### ISSUE TITLE
Show formatted numbers in the paging when over 1,000 pages

### ISSUE THREAD

**Issue by mpGitHub** [michaelbromley/ngx-pagination#307]
**Angular version**: 
5.2.11

**ngx-pagination version**:
3.2.1

**Description of issue**:
The paging numbers do not have commas in it when the number of pages go past 1,000.
So the number displays as 4300 instead of 4,300. 
(We use Server-Side Paging in our app so the number of pages can be large)

**Steps to reproduce**:
Set the totalItems to be a large number like 20,000 and make the itemsPerPage to be 5. 

**Expected result**:
Show commas in the button page links for easy reading

**Actual result**:
The pages displayed in the button selection will not have commas in the number.

**Demo**: 
Here is a demo
https://angular-upmtxc.stackblitz.io

Any relevant code:
```

```

**Comment by michaelbromley** [comment]
This would be a good enhancement. It could be done with the the built-n [Angular number pipe](https://angular.io/api/common/DecimalPipe) in [this part of the template](https://github.com/michaelbromley/ngx-pagination/blob/d9c8bff96807f79c4548e9a49f04d6864db40ff8/src/template.ts#L35-L39).

I've not got time to do this right now, but I'll mark it as a good first issue and see if anyone wants to tackle it before I get round to it.

In the meantime if you really need this formatting right now, you'd have to use a [custom template](https://github.com/michaelbromley/ngx-pagination#paginationcontrolsdirective).

**Comment by michaelbromley** [comment]
Fixed by #309
