### ISSUE TITLE
Is it possible to not use ellipsis in ngx-pagination?

### ISSUE THREAD

**Issue by minicatsCB** [michaelbromley/ngx-pagination#313]
**Angular version**: 5.2.9

**ngx-pagination version**:4.0.0

**Description of issue**:
I'm using ngx-pagination package and trying to implement this:

![pagination-1](https://user-images.githubusercontent.com/19836547/60895403-e42b8f00-a264-11e9-9960-b1733866aaca.png)

But this is what I have until now:

![pagination-2](https://user-images.githubusercontent.com/19836547/60895418-ed1c6080-a264-11e9-85b4-4a7d30c23d60.png)

My HTML:
``` html
<pagination-controls responsive="true" directionLinks="false"></pagination-controls>
```

My CSS:
```scss
.ngx-pagination {
    .current {
        background: orange;
    }
}
```

- Do you know if would it be possible to put more space between the different items? Thus incrementing the width of the component.
- In case of more width available, show more numbers instead of ellipsis (...).
- Show a dot (like a bullet) between the numbers. For this I have found this. But doesn't work well, it shows the dots below the numbers. Only works for the current number. See below:
![pagination-3](https://user-images.githubusercontent.com/19836547/60896090-04a81900-a266-11e9-98b6-54c4de262f21.png)

Stackblitz: https://stackblitz.com/edit/angular-xbh9ft

**Comment by michaelbromley** [comment]
Hi!

For the styling, you can either override the CSS styles (which I see you have attempted in the StackBlitz) or, if you want more control, create your own [custom template](https://github.com/michaelbromley/ngx-pagination#paginationcontrolsdirective) so you have full control over the markup.

Based on the desired style in your first image, I'd say you'd probably need to go with a custom template to get that effect with the dots in between the numbers.

> In case of more width available, show more numbers instead of ellipsis (...).

There is the [`maxSize` input](https://github.com/michaelbromley/ngx-pagination#paginationcontrolscomponent) which will cause more pages to be displayed before using the ellipsis.

**Comment by minicatsCB** [comment]
Thank you for your help! It was very useful! I hadn't thought about making my own template. Now, I achieved exactly what I wanted. I leave this Stackblitz in case it is useful for someone: https://stackblitz.com/edit/angular-w7vhcw.

As a detail, I have observed this DOM element inside the `<pagination-controls>` (the default, not the custom one) that, I guess, is for **responsive** mode:

```html
<li class="small-screen">
    5 / 10
</li>
```

Would it be also possible to make a custom template for small screens?

**Comment by michaelbromley** [comment]
Glad it helped you!

> As a detail, I have observed this DOM element inside the <pagination-controls> (the default, not the custom one) that, I guess, is for responsive mode:

Yes, that's right.

For small screen support in your custom template, you can just include the markup in the same custom template, and use CSS to show or hide it with a media query. Here's how the default template markup/css looks:

```html
 <li class="small-screen">
    {{ p.getCurrent() }} / {{ p.getLastPage() }}
 </li>
```

```css
@media screen and (max-width: 601px) {
  .ngx-pagination.responsive .small-screen {
    display: inline-block; } 
  .ngx-pagination.responsive li:not(.small-screen):not(.pagination-previous):not(.pagination-next) {
    display: none; }
}
```

**Comment by minicatsCB** [comment]
Thank you again and for your fast help! I got it!

I updated the Stackblitz: https://stackblitz.com/edit/angular-bxvecv

**Comment by michaelbromley** [comment]
Looks good! You can close this issue if you have no further questions.
