### ISSUE TITLE
Mutliple controls in same page 

### ISSUE THREAD

**Issue by ACBNair** [michaelbromley/ngx-pagination#318]
**Angular version**: 8.0

**ngx-pagination version**: 4.1.0

**Description of issue**: Multiple controls in same page not working properly.

**Steps to reproduce**: Try adding one more item in https://stackblitz.com/edit/angular-e1f9hq?file=app%2Fapp.component.html itself.

**Expected result**: Controls shall work independantly.

**Actual result**:

**Demo**: (if possible, edit [this StackBlitz demo](https://stackblitz.com/edit/angular-e1f9hq) and paste the link to your fork)

Any relevant code:
```
<div class="list">
		<ul>
			<li *ngFor="let item of collection | paginate: { itemsPerPage: 10, currentPage: p }">{{ item }}</li>
		</ul>

    <ul>
			<li *ngFor="let item of collection1 | paginate: { itemsPerPage: 25, currentPage: q }">{{ item }}</li>
		</ul>
		<pagination-controls (pageChange)="p = $event"></pagination-controls>

    <pagination-controls (pageChange)="q = $event"></pagination-controls>
</div>
```

**Comment by michaelbromley** [comment]
Hi,

Please refer to the docs: https://github.com/michaelbromley/ngx-pagination#multiple-instances

In particular: 

> It is possible to have any number of pagination pipe/controls pairs in the same template. To do this, just make use of the "id" attribute:

**Comment by MiRush94** [comment]
Think this should be closed, clearly not a bug with ngx pagination itself, no?

**Comment by michaelbromley** [comment]
@MiRush94 yes indeed!
