### ISSUE TITLE
How can i stop the auto refresh of data from one page to another page?

### ISSUE THREAD

**Issue by ShashankM3-hexaware** [michaelbromley/ngx-pagination#319]
Hi, thanks for contributing!

This project is maintained in my spare time, so in order to help me address your issue as quickly as 
possible, please provide as much of the following information as you can.

-- Michael 

[^ delete this message]

=======

**Angular version**:

**ngx-pagination version**:

**Description of issue**:

**Steps to reproduce**:

**Expected result**:

**Actual result**:

**Demo**: (if possible, edit [this StackBlitz demo](https://stackblitz.com/edit/angular-e1f9hq) and paste the link to your fork)

Any relevant code:
```

```

**Comment by michaelbromley** [comment]
Hi. Please edit your issue and include the requested information according to the issue template. Otherwise I cannot help.

**Comment by michaelbromley** [comment]
I'm closing this issue because further data was needed but was not provided. If you want to continue the thread, let me know and I'll re-open it.
