### ISSUE TITLE
paginate: { itemsPerPage: 1, currentPage: p }" not working along with index in ngFor

### ISSUE THREAD

**Issue by iamakashaher** [michaelbromley/ngx-pagination#333]
**Angular version**: 8.2

**ngx-pagination version**: 4.1.0

**Description of issue**: Cannot use paginate: { itemsPerPage: 1, currentPage: p }" along with index and array in ngFor.

**Steps to reproduce**:
        *ngFor="let question of questions; let index = index; | paginate: { itemsPerPage: 1, currentPage: p }">

**Expected result**:
It should show pagination where pagination control mentioned.

**Actual result**: 
Parser Error: Unexpected token |, expected identifier, keyword, or string at column 47 in [let question of questions; let index = index; | paginate: { itemsPerPage: 1, currentPage: p }] in ng:///AdminLayoutModule/QuestionBankComponent.html@4:8 ("et index = index; | paginate: { itemsPerPage: 1, currentPage: p }">

**Demo**: (if possible, edit [this StackBlitz demo](https://stackblitz.com/edit/angular-e1f9hq) and paste the link to your fork)

Any relevant code:
```

```

**Comment by michaelbromley** [comment]
Hi,

This is covered in the README: https://github.com/michaelbromley/ngx-pagination#how-do-i-use-the-ngfor-index-with-the-pagination-pipe

**Comment by iamakashaher** [comment]
Hi @michaelbromley,
Thank you for the quick update.
