### ISSUE TITLE
CSS Not applied to pagination control

### ISSUE THREAD

**Issue by iamakashaher** [michaelbromley/ngx-pagination#336]
**Angular version**: 8

**ngx-pagination version**: ^4.1.0

**Description of issue**: I applied custom CSS to paginate control, but it not get applied. I tried /deep/but it gives an error. can you please tell me an alternative method or any feasible solution.

**Steps to reproduce**: Apply custom CSS to paginate the previous next button.

**Expected result**: CSS should get applied/

**Actual result**: No effect.

Any relevant code:
```
.pagination-previous .ng-star-inserted{
  background-color: coral !important;
  border-radius: 15px !important;
  color: black !important;
}

```

**Comment by michaelbromley** [comment]
Hi,

> I tried /deep/but it gives an error.

What error?

Also, please try to put together a Stackblitz reproduction, otherwise it is hard for me to help. I don't have time to attempt to reproduce the issue normally. Thanks!
