### ISSUE TITLE
Need Version 3.0.3 Source

### ISSUE THREAD

**Issue by preyan** [michaelbromley/ngx-pagination#337]
Hi,

Can someone provide me the source of version 3.0.3. Thanks in advance.

**Comment by michaelbromley** [comment]
Hi,

Here you go: https://github.com/michaelbromley/ngx-pagination/tree/d8d105a98ca1ef641c310e1e1190c853c4d2cfd6

Why do you need this, may I ask?

**Comment by preyan** [comment]
Hi Michael,

Thanks for the help. 

I had used v3.0.3 for one of my personal projects and made some changes to the library itself. I needed this source to compare the changes I have made previously and upgrade to the latest version of ngx-pagination.
