### ISSUE TITLE
Selected Page Number is Not highlighted

### ISSUE THREAD

**Issue by shruthih19** [michaelbromley/ngx-pagination#341]
Hi, thanks for contributing!

This project is maintained in my spare time, so in order to help me address your issue as quickly as 
possible, please provide as much of the following information as you can.

-- Michael 

[^ delete this message]

=======

**Angular version**: 5.2.2

**ngx-pagination version**: 4.1.0

**Description of issue**: On Select of a particular page number , that page is not getting selected

**Steps to reproduce**: On select of a particular page I want to make a server call in my application and highlight the selected page which is not happening.
https://stackblitz.com/edit/ngx-pagination-n3mwr5?file=app/app.component.ts

**Expected result**:

**Actual result**:

**Demo**: https://stackblitz.com/edit/ngx-pagination-n3mwr5?file=app/app.component.ts

Any relevant code:
```

```

**Comment by michaelbromley** [comment]
Hi,

Thanks for providing a reproduction. Your code is not using this library in the correct way. Please re-read the documentation (https://github.com/michaelbromley/ngx-pagination#quick-start) which shows you how this library is supposed to be used. Try your best to follow it and let me know if you still have trouble.

**Comment by shruthih19** [comment]
Hi,

Solution is set the pageNumber on Pagechange event
