### ISSUE TITLE
Need to Show 2 pages forward and back with middle selected tab

### ISSUE THREAD

**Issue by abhishek070189** [michaelbromley/ngx-pagination#343]
Tried on below splunker 
http://embed.plnkr.co/ofLDnQI9PTUDpfvOJHod/

I am trying to achieve that 2 previous & 2 next pages number should show with the selected tab in middle, currently we are showing 1 previous & 1 next pages only.  So i tried by using custom template as well but unable to find any solution. Kindly help as its bit important.

**Comment by michaelbromley** [comment]
Hi,

Do you mean you want the pagination controls to look like this?

```
<< 1 ... 7 8 [9] 10 11 ... 22 >>
```

If so, try changing setting `[maxSize]="9"` on the controls component/directive.

**Comment by abhishek070189** [comment]
thanks @michaelbromley for quick reply. I got your point but when I am implementing it thru custom template in my project that p.pages coming as null (due to this pagination numbers are not coming). Below is my code :
<pagination-template #p="paginationApi" [id]="config.id" (pageChange)="config.currentPage = $event">
                <div class="custom-pagination">
                  <div class="pagination-previous" [class.disabled]="p.isFirstPage()">
                    <a *ngIf="!p.isFirstPage()" (click)="p.previous()">
                      < </a> </div> <div *ngFor="let page of p.pages" [class.current]="p.getCurrent() === page.value">
                        <a (click)="p.setCurrent(page.value)" *ngIf="p.getCurrent() !== page.value">
                          <span>{{ page.label }}</span>
                        </a>
                        <div *ngIf="p.getCurrent() === page.value">
                          <span>{{ page.label }}</span>
                        </div>
                  </div>

                  <div class="pagination-next" [class.disabled]="p.isLastPage()">
                    <a *ngIf="!p.isLastPage()" (click)="p.next()"> > </a>
                  </div>
                </div>

              </pagination-template>

**Comment by abhishek070189** [comment]
> Hi,
> 
> Do you mean you want the pagination controls to look like this?
> 
> ```
> << 1 ... 7 8 [9] 10 11 ... 22 >>
> ```
> 
> If so, try changing setting `[maxSize]="9"` on the controls component/directive.

Can we use this maxSize in below control 
 <pagination-controls (pageChange)="pageChanged($event)" responsive="false" autoHide="true">
              </pagination-controls>

**Comment by abhishek070189** [comment]
> > Hi,
> > Do you mean you want the pagination controls to look like this?
> > ```
> > << 1 ... 7 8 [9] 10 11 ... 22 >>
> > ```
> > 
> > 
> > If so, try changing setting `[maxSize]="9"` on the controls component/directive.
> 
> Can we use this maxSize in below control
> <pagination-controls (pageChange)="pageChanged($event)" responsive="false" autoHide="true">

It worked for me with below code
<pagination-controls (pageChange)="pageChanged($event)" maxSize="9" responsive="false" autoHide="true">
              </pagination-controls>

Now issue is that on load its showing 1-7 pages, instead i need it 1-5 pages

**Comment by abhishek070189** [comment]
@michaelbromley : any approach which i can take to achieve above result ?

**Comment by abhishek070189** [comment]
> > > Hi,
> > > Do you mean you want the pagination controls to look like this?
> > > ```
> > > << 1 ... 7 8 [9] 10 11 ... 22 >>
> > > ```
> > > 
> > > 
> > > If so, try changing setting `[maxSize]="9"` on the controls component/directive.
> > 
> > 
> > Can we use this maxSize in below control
> > <pagination-controls (pageChange)="pageChanged($event)" responsive="false" autoHide="true">
> 
> It worked for me with below code
> <pagination-controls (pageChange)="pageChanged($event)" maxSize="9" responsive="false" autoHide="true">
> Now issue is that on load its showing 1-7 pages, instead i need it 1-5 pages

Please reply as m stuck here how to achieve this ?

**Comment by abhishek070189** [comment]
@michaelbromley Any update pls ...

**Comment by michaelbromley** [comment]
Hi, I don't quite understand some of your messages above. The best thing would be to recreate what you have so far by forking [this StackBlitz demo](https://stackblitz.com/edit/angular-e1f9hq) and then I can better understand the issue now.

**Comment by abhishek070189** [comment]
> Hi, I don't quite understand some of your messages above. The best thing would be to recreate what you have so far by forking [this StackBlitz demo](https://stackblitz.com/edit/angular-e1f9hq) and then I can better understand the issue now.

Below is the code which I am trying :
```
<div class="list">
		<ul>
			<li *ngFor="let item of collection | paginate: { itemsPerPage: 5, currentPage: p }">{{ item }}</li>
		</ul>

		<pagination-controls (pageChange)="p = $event" maxSize=9></pagination-controls>
</div>
```
**Output** 
By using maxSize I am able to achieve 2 back and 2 forward pages with selected page but
Starting 1,2,3,4,5,6,7 pages showing but my requirement is to show only 5 pages i.e 1,2,3,4,5 only

**Comment by michaelbromley** [comment]
Maybe something like this is what you are looking for? https://stackblitz.com/edit/angular-nsabrn

**Comment by abhishek070189** [comment]
> Maybe something like this is what you are looking for? https://stackblitz.com/edit/angular-nsabrn

Thanks for ur reply @michaelbromley . I already tried this approach but it didn't solve my problem. It solves my initial load problem i.e to show 5 pages on load but on click of fifth element it adds next 6,7 pages instead of showing three dots (...). that is the place where m not getting any solution till now. My need is that while m clicking on fifth element than result should be look like----               
1 ... 3 4 **5** 6 7 ... 11

**Comment by michaelbromley** [comment]
Ok, then I think the only way to do this would be to create your own template with particular custom logic which causes the links to display exactly how you need them to.

**Comment by abhishek070189** [comment]
> Ok, then I think the only way to do this would be to create your own template with particular custom logic which causes the links to display exactly how you need them to.

thanks for ur efforts.
