### ISSUE TITLE
Can we select the items in the current page since the ngFor will not know about the re-arranged items in the list.?

### ISSUE THREAD

**Issue by sumin27** [michaelbromley/ngx-pagination#345]
Hello Contributors,

=======

**Angular version**: 7.2.0

**ngx-pagination version**: 3.2.1

**Description of issue**: I was trying to select only the items in the current page. Since ngFor is unaware of the positioning of the list items, i am unable to get the list items in the current page. Can you please suggest if there is any way to achieve this. The functioning expected would be similar to the select all option we have in Gmail.

**Steps to reproduce**: 

**Expected result**: Added an option to select all of the current page, but unable to find any options to get only the items of the current page.

Regards,
Sumin.

**Comment by michaelbromley** [comment]
Hi,

The items of the current page can be derived from the current values of the `currentPage` and `itemsPerPage`. For example, if you are on page 5, and there are 10 items per page, then you know that the items on the page would be items 51 - 60.

Does this answer your question?

**Comment by sumin27** [comment]
Hi Michael, 

As mentioned in the FAQ section, I have tried doing that as well, using
{{ itemsPerPage * (currentPage - 1) + i }}

but unfortunately this would only give me the absolute index value. While I am at page 5 and supposedly i want to select the items 51-60, the ngFor(with filter/sort applied) would have different items in these indexes. Since the list is a certain sorted/filtered order, my attempt was to get the items in page 5 which would not necessarily have indexes 51-60.

Thanks for the prompt response. Glad to discuss further if my explanation isn't clearing the picture of my query.

Regards,
Sumin.

**Comment by michaelbromley** [comment]
Hi,

Ok, I see how the sorting & filtering would complicate matters. I suggest that you try to reproduce the issue using the StackBlitz demo provided, and show what you have attempted so far. In this way I'll better be able to assist. Another option is to try something like StackOverflow (since this issue is more of a support request rather than a bug or feature request).

**Comment by sumin27** [comment]
Hi Michael,

Here is a stackblitz demo and the expected versus actual result of the problem statement. I hope this helps clarify. 

https://stackblitz.com/edit/angular-auaxwl?file=src%2Fapp%2Fapp.component.ts

When i do Select All here:
![pg1](https://user-images.githubusercontent.com/19794955/71062231-1a652700-2192-11ea-9974-c54cfe613ec3.PNG)

**Expected Behavior:**
![pg2](https://user-images.githubusercontent.com/19794955/71062279-3b2d7c80-2192-11ea-8fd1-030dce05c3c0.PNG) -PG3 (should be selected)
![pg4](https://user-images.githubusercontent.com/19794955/71062296-42548a80-2192-11ea-9a1f-e0f53f348222.PNG) -PG5 (should not be selected)

**Actual Behavior**
![pg2](https://user-images.githubusercontent.com/19794955/71062319-4ed8e300-2192-11ea-8473-06d584a51e8f.PNG) -PG3 (should be selected => is selected)
![pg3](https://user-images.githubusercontent.com/19794955/71062335-54cec400-2192-11ea-8ae3-b631c7d902ab.PNG) -PG5 (should not be selected => is also selected)

Thanks for the support. Yes i do agree that this is support on implementation rather than bug/feature request here. But i was trying make sure that i am not missing any thing out that is already provided here.

Regards,
Sumin.

**Comment by michaelbromley** [comment]
Hi Sumin,

Thanks for the demo, that gives me a better picture of the problem. There's no special way provided by this lib to do what you want. I managed to kind of hack a way to do it, see: https://stackblitz.com/edit/angular-3bcvls?file=src%2Fapp%2Fapp.component.ts

The idea is to attach the index to each table row, and when selecting all you can query the current visible elements via a `ViewChildren` query and retrieve the currently-displayed items.

Perhaps this will be useful to you, or give you some more ideas of different ways to solve the problem.

**Comment by sumin27** [comment]
Thanks Michael. This perfectly makes sense and would add value to what i am trying to achieve.
