### ISSUE TITLE
How can I get the number of pages?

### ISSUE THREAD

**Issue by SeniorFlacko** [michaelbromley/ngx-pagination#346]
** Angular 8.3.3**:

**5.0.0**:

**I need to display how many pages are available, like the message 'Page 1 of [number_here] ' **:

**Comment by michaelbromley** [comment]
Hi,

What have you tried so far? Generally this would be done with something like `Math.ceil(collectionLength / itemsPerPage)`

**Comment by SeniorFlacko** [comment]
Yeah I used the division approach!
