### ISSUE TITLE
Absolute row index does not return correct value with filter

### ISSUE THREAD

**Issue by Sowmya-Sukhanand** [michaelbromley/ngx-pagination#363]
Iam calculating the absolute index with the formula
this.itemsPerPage * (this.currentPage - 1) + indexOnPage;
It works perfectly
But when i apply search and filter out the results,the actual index of the filtered result is not being displayed.It displays the index of the fitered result irrespective of the page in which it is being displayed.

**Comment by michaelbromley** [comment]
Hi,
Can you show some code? Ideally a stackblitz reproduction of the issue?

**Comment by Sowmya-Sukhanand** [comment]
Hii.Thanks for getting back!!!
Unfortunately iam not able to reproduce the issue due to some technicality

**Comment by Sowmya-Sukhanand** [comment]
Hii.Thanks for getting back!!!
Unfortunately iam not able to reproduce the issue due to some technicality
Anyways i've solved the issue by not using the absolute index as of now
