### ISSUE TITLE
How to create or customize the feature choosing the items per page like that ? 

### ISSUE THREAD

**Issue by tungphamhttt1** [michaelbromley/ngx-pagination#367]
Hi
I am wondering how can i create or customize the feature choosing the items per page like that in project
![image](https://user-images.githubusercontent.com/40782852/93291490-6de1cf80-f80d-11ea-9120-c759b55b0f98.png)
Thank you.

=======

**Comment by michaelbromley** [comment]
Hi,

The basic idea is to bind the "items per page" select input to the variable used to set the itemsPerPage in the pagination config.

**Comment by tungphamhttt1** [comment]
ok, thank so much.
