### ISSUE TITLE
Pagination got stuck in recursive call when make api calls on paginate

### ISSUE THREAD

**Issue by lakhwindergill** [michaelbromley/ngx-pagination#377]
Hi,

**Angular version**: 10

**ngx-pagination version**:^5.1.1

**Description of issue**: I am using mat-accordion with ngx-pagination. If I make an API call on the paginate, it got stuck in a recursive call. with API call it works.

```ts
export class myService {
    constructor(private httpService: HttpService) {}

    get(
        serviceRequest: ServiceRequest
    ): Observable<serviceResponse> {
        let url = `myAPiUrl?source=${serviceRequest.source}&pageSize=${serviceRequest.pageSize}&pageNumber=${serviceRequest.pageNumber}`;

        return this.httpService.get(url);
    }
}
```
--------Call on paginate------------------------------
```ts
public loadServiceData
(
        pageNumber: number
    ): void {
        this.pageNumber = pageNumber;
        this.serviceRequest= {          
            pageSize: this.pageSize,
            pageNumber: pageNumber,
        };
        this.serviceResult= null;
        this.myService .get(this.serviceRequest).subscribe(
            (response: serviceResponse) => {
                this.responseData= response.data;
                this.totalCount= response.totalCount;
                
            },
            (error) => {
                //Error handling goes here.
                this.formErrorDisplayMessage = this.handleErrorResult(
                    null,
                    error,
                    "Failure"
                );
               
            },
            () => {
                // Request completed.
            }
        );
    }
```
-----------------------------------
```ts
paginate()
{
this.loadServiceData();
If I use don't make an API call it works fine..... but I have to fetch data on every button click

}
```

---------------UI_-------------------------------------
```html
 <mat-accordion multi *ngFor="let responseof responseData| paginate: {
            itemsPerPage: pageSize,
            currentPage: pageNumber,
            totalItems: totalCount, id: 'paginator'
        } ">
```

**Comment by michaelbromley** [comment]
Hi,

I am not familiar with the mat-accordian component. It is not apparent to me what is triggering the `paginate()` call. Can you put together a minimal reproduction of the issue on Stackblitz?

**Comment by lakhwindergill** [comment]
Thank you for your reply @michaelbromley !
I am able to resolve it. It was not accordion issue, it is happening with other controls also. I have to place a check in my component to stop the recursive call. 

public pageNumberChanged(pageNumber: number) {
        if (pageNumber != this.currentPage && this.filterData) {
            this.currentPage = pageNumber;
            this.pageChanged.emit(pageNumber);
        }
        else {
            this.pageChanged.emit(pageNumber);
        }
    }

I have a custom control that uses ngx-pagination. Which can be used on list pages that filters that data locally and and can make API calls on next button click.

**Comment by michaelbromley** [comment]
Glad to hear you got it fixed, and thanks for sharing your solution!
