### ISSUE TITLE
maxSize cannot be below 5

### ISSUE THREAD

**Issue by MathieuLavigneOpen** [michaelbromley/ngx-pagination#378]
**Angular version**: 11.0.0

**ngx-pagination version**: 5.1.1

**Description of issue**: Current page is not visible if maxSize is below 5

**Steps to reproduce**: Use pagination in a context where there are at least 5 pages. Set maxSize to 4. Go to middle pages, for instance page 4, with next page button.

**Expected result**: The current page number is visible no matter the current page.

**Actual result**: The current page number is not visible when it is in the middle (for instance 3).

**Demo**: (if possible, edit [this StackBlitz demo](https://stackblitz.com/edit/angular-e1f9hq) and paste the link to your fork)

Any relevant code:
```

```

# Screenshots

Current page = 4/7

maxSize = 5 :

![image](https://user-images.githubusercontent.com/82509249/128168758-1ef80150-51b0-4ccf-aecb-8b96fc8ef80d.png)

maxSize = 4 :

![image](https://user-images.githubusercontent.com/82509249/128168860-b6a82dbd-edc2-4eb1-b2b0-0b0deebfd99d.png)

# Suggested solution

It may be written in the docs that maxSize cannot be below 5.

**Comment by michaelbromley** [comment]
Thanks for the report. Would you like to create a PR which adds this line to the readme?
