### ISSUE TITLE
Angular 14 npm install error

### ISSUE THREAD

**Issue by magicnov** [michaelbromley/ngx-pagination#390]
I`m getting error while installing package on angular 14

![image](https://user-images.githubusercontent.com/54899018/173606794-01eab8f8-89a6-4772-9c3c-ca10415fcae9.png)

**Comment by alonsobn13** [comment]
Tengo el mismo error, algún soporte?

**Comment by michaelbromley** [comment]
I just published v6.0.2 which should resolve this issue.
