### ISSUE TITLE
Moving the previous and next buttons

### ISSUE THREAD

**Issue by Exemocaro** [michaelbromley/ngx-pagination#391]
**Angular version**:
14.0.5

**ngx-pagination version**:
6.0.2

Is it possible to move the previous and next buttons away from the numbers?
For example:

`Previous_________________________________1 2 3 ... 50 _________________________________Next`

**Comment by Cavalex** [comment]
I actually managed to do it by doing this: 
```
.my-pagination /deep/ .ngx-pagination{
    display:flex;
    align-content: center;
    justify-content: center;
    padding: 0;
}

.my-pagination /deep/ .ngx-pagination .pagination-previous{
    margin-right:auto;
}

.my-pagination /deep/ .ngx-pagination .pagination-next{
    margin-left:auto
}

```
