### ISSUE TITLE
Can't bind to 'ngForPaginate' since it isn't a known property of 'li' (used in the 'ListingComponent' component template).

### ISSUE THREAD

**Issue by AlphaRomeoMike** [michaelbromley/ngx-pagination#397]
```
Angular CLI: 14.2.2
Node: 18.7.0 (Unsupported)
Package Manager: npm 8.15.0
OS: win32 x64

Angular: 14.2.1
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1402.2
@angular-devkit/build-angular   14.2.2
@angular-devkit/core            14.2.2
@angular-devkit/schematics      14.2.2
@angular/cli                    14.2.2
@schematics/angular             14.2.2
rxjs                            7.5.6
typescript                      4.7.4
```

ngx-pagination: 6.0.2

### Description
Once I import the `NgxPaginationModule` and implement the paginate pipe with async pipe when reading the data from stream, I get the error that is mentioned in the title.

### Steps to Reproduce
- Declare `page` property as a number and set default to 1
- Parse the data to the stream as an observable and extract it with async pipe.

### Expected result 
- Paginated data with form controls should be shown

### Actual result
- Unpaginated data is shown 

### Demo: 
- [This is my StackBlitz Demo](https://angular-jfjqov.stackblitz.io)

**Comment by michaelbromley** [comment]
Your demo was using incorrect syntax:

```
let news of news$ | async,  paginate: { itemsPerPage: 10, currentPage: page }
```

the comma after the async pipe should be a pipe character.

**Comment by AlphaRomeoMike** [comment]
Thank you :)
