### ISSUE TITLE
Error while using the package in the Angular 10

### ISSUE THREAD

**Issue by gouseferoz** [michaelbromley/ngx-pagination#399]
Hi, I have imported the package in my Angular 10 Project and I see the below error message

```
./node_modules/ngx-pagination/fesm2015/ngx-pagination.mjs 596:5219-5245
Can't import the named export 'ChangeDetectionStrategy' from non EcmaScript module (only default export is available)
```

Can you help me how to fix this issue?

Regards,
Feroz

**Comment by michaelbromley** [comment]
See the note [here](https://github.com/michaelbromley/ngx-pagination#angular-version):

> This library is built to work with Angular 13+. If you need to support an earlier version of Angular, please use v5.x.
