### ISSUE TITLE
the specified id "mlistPaging" does not match any registered PaginationInstance

### ISSUE THREAD

**Issue by sushantsavvase** [michaelbromley/ngx-pagination#406]
Facing issue with Angular: "17.1.2", ngx-pagination: "6.0.3",
Look at the below image

![image](https://github.com/michaelbromley/ngx-pagination/assets/83905177/e2e372c6-a722-419f-81ab-5280bb4a62c2)

**Comment by michaelbromley** [comment]
Please provide a reproduction

**Comment by sushantsavvase** [comment]
Thanks for your reply.

Now the issue is resolved for me. I had added the wrong id to the pagination control.

Thanks.
